### ISSUE TITLE
Moving the settings under Settings/Appearance 

### ISSUE THREAD

**Issue by vyskoczilova** [envato/wp-envato-market#100]
Have you ever thought about moving the setting page under Settings/Appearance/Plugin menu item? All the time using this plugin I think it's way too exposed - you need to do just one-time setting and than you can forget about it. Like that it takes space and there is no reason to make it first-hand accessible.

What do you think? If it will be ok, I would love to make a pull request with the moved menu item.

**Comment by dtbaker** [comment]
Thanks for the suggestion. We'll take it on board for the next update.
