### ISSUE TITLE
are you sure you want to do this? Please try again.

### ISSUE THREAD

**Issue by sbwoodside** [envato/wp-envato-market#101]
- I have a fresh install of WP 4.7.4 and Envato Market 1.0.0-RC2.
-  I have a number of themes purchased from Envato that show up in the Envato Plugin market.
- Go to `Envato Market` > `Themes`
- click `Install`
- Enter hostname, FTP username, FTP password, click FTPS (SSL), click `Proceed`
- the following message appears:

> Are you sure you want to do this?
> 
> Please try again.

Clicking `Please try again` just takes me back.

**Comment by dtbaker** [comment]
We have a fix for this coming out in the next few days. 

If that doesn't work please try putting `define('FS_METHOD', 'direct');` into your wp-config.php in the website home directory.
