### ISSUE TITLE
Plugin slowing website and giving Timeout errors

### ISSUE THREAD

**Issue by wordpressman** [envato/wp-envato-market#102]
Hi,

I was building a website for a client and after having many issues with Timeout errors, found that Envato-Market 1.0.0-RC2 plugin was the culprit.

FYI, here is the configuration:

WP 4.7.4 with Total Theme using PHP 7 and SSL Let's Encrypt.

Plugins:
Contact Form 7 - Version 4.7	Active
Duplicate Post - Version 3.2	Active
Email Address Encoder - Version 1.0.5	Active
Envato Market - Version 1.0.0-RC2	Inactive
Google Analytics - Version 2.1.3	Active
Google Analytics Dashboard for WP - Version 4.9.6.2	Inactive
Google Analytics for WordPress by MonsterInsights - Version 6.1.7	Inactive
SG Optimizer - Version 3.3.1	Active
Slider Revolution - Version 5.4.1	Active
Templatera - Version 1.1.12	Inactive
TinyMCE Advanced - Version 4.5.6	Active
UpdraftPlus - Backup/Restore - Version 1.12.40	Active
Wordfence Security - Version 6.3.8	Active
WPBakery Visual Composer - Version 5.1	Active
WPML Media - Version 2.2.0	Active
WPML Multilingual CMS - Version 3.7.0	Active
WPML String Translation - Version 2.5.3	Active
WP Smush - Version 2.6.3	Active
Yoast SEO - Version 4.7     Active

**Comment by dtbaker** [comment]
We have a fix for this coming out in the next few days.
