### ISSUE TITLE
'Test API Connection' does nothing at all

### ISSUE THREAD

**Issue by ossigeno** [envato/wp-envato-market#103]
It really must do better than simply reload the page with nothing displayed. It looks amateurish. Display some sort of message at least success or failure.

Also not keen on using Release Candidate software in a production environment.

**Comment by ossigeno** [comment]
RC 2.0 for 12 months. Any plan for a production version?

**Comment by aero2graph** [comment]
Not working.
"The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions."

**Comment by dtbaker** [comment]
We have a fix for this coming out in the next few days.
