### ISSUE TITLE
Update not showing up on plugin

### ISSUE THREAD

**Issue by christyherself** [envato/wp-envato-market#105]
First, I did read through this thread:  https://github.com/envato/wp-envato-market/issues/54

I got an email from envato that "premium plugin" needs update.  I have this "premium plugin" on 4 sites and the last time it had an update, I was able to use this plugin to update it.  However, this time when I go to Envato Market - Plugins - it does not have the standard outline that says an update is available.

I looked on the files available for download with this theme, and it does say "installable wordpress file only" on the list of options for download, so I don't think it is that the plugin author hasn't made an installable zip file available.

Any suggestions on what I might be overlooking?  Thanks in advance for your help.  I know I can delete the plugin and reinstall it but I really prefer using this plugin.  :)  On a side note - on two of these sites, updates were available on themes and I was able to use this plugin to update them TODAY.

**Comment by garymgordon** [comment]
Did we get an answer to this yet? Please let me know.  I'm having the same issue.
Gary

**Comment by christyherself** [comment]
Honestly...it's been awhile but I think it is something that finally resolved itself.  Sorry I'm not of any additional help.

**Comment by garymgordon** [comment]
Christy,  Thanks for providing the update. I just had a plugin from Envato that I purchased.  And after recently installing the Envato plugin (so I could easily see in my WP Dashboard, when the Envato plugin had an update available) it's just not working.  And as of now (9/14/2017) it's not working.  So if anyone knows why this might be, I'd appreciate any help. Thanks.

**Comment by christyherself** [comment]
Well as an update...I have another client site that I've installed this on with the hopes that Visual Composer would update but it is not updating it.

**Comment by garymgordon** [comment]
Christy,

FYI.  It seemed to work today for no apparent reason.  My FAST support
plugin (from CodeCanyon) showed up in WP Plugins and updated successfully.
I'm happy, but sceptical as to whether or not it will continue to work in
the future.  I'll keep my fingers crossed.

Gary

**Comment by dtbaker** [comment]
We have a fix for this coming out in the next few days.
