### ISSUE TITLE
Token Not Verified

### ISSUE THREAD

**Issue by rindoshingen** [envato/wp-envato-market#106]
Hey folks, 

Create a brand new token, but each time I get this ...

> The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions.

When I try to install a theme or plugin, I get this: Install package not available.

Thoughts?

**Comment by Kiwi1919** [comment]
Same issue here, finding an answer from anyone is proving difficult!.

**Comment by aero2graph** [comment]
Not working. Same with me.
"The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions."

**Comment by dtbaker** [comment]
We have a fix for this coming out in the next few days.
