### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by piazawa** [envato/wp-envato-market#108]
I have used this plugin on several sites, but today it suddenly stopped working. What happened?

**Comment by david-maxwell** [comment]
Doesn't seem to be working . :-(

**Comment by just-us** [comment]
I have a similar issue, have you stopped updating this plugin? I get several errors in PHP 7

**Comment by ezflo** [comment]
this still is not resolved, plug in does not work, unable to update theme
![betheme](https://user-images.githubusercontent.com/29875770/27815605-d8e3e8ac-60c8-11e7-8656-1929523ec5c2.PNG)

**Comment by ezflo** [comment]
Is there anybody who moderates this site or are all entries in vain?? Anybody???

**Comment by JosKlever** [comment]
@ezflo, I'm just a user of this plugin, but as your screenshot shows, the plugin workshop. Hoever I als know BeTheme and if you would have read the changelog and/or theme information, you would know that you have to use the registratienummer option within the theme option to get all the updates including the theme's plugins.

The only think Envato Market plugin does is creatief a link between your website and your Envato account. Whether updates will succeed  after that, is depending on what the theme or plugin maker is offering. If it's not working, it might be an issue on your website, with your license, with missing installation files etc.

**Comment by JosKlever** [comment]
I'm still using this plugin daily, also with PHP7.

**Comment by ezflo** [comment]
Hi Jos,

After a day of futile attempts at getting the plug in working, found that
Betheme 20 now does auto updates, which makes the plug in defunct.

Got my site updated and at the end of he day am happy it has been resolved.

There are no clear entry and exit points for a lot of this software
especially if you only admin once a month or so.

thanks for assisting

Regards


*Pieter Oosterhoff*
DIRECTOR


Email info@ezflo.com.au
Tel +61 7 4778 0180
10 Fryers Road HERVEY RANGE Queensland Australia 4817
NQ Visions Pty Ltd trading as EZFLO Fertilising Australia

www.ezflo.com.au



This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by dtbaker** [comment]
Hey @ezflo , @just-us , @piazawa you are welcome to test this copy of the plugin.

Please delete the old `Envato Market` plugin from your WordPress installation and then add this attached plugin ZIP: 
[envato-market.zip](https://github.com/envato/wp-envato-market/files/1782074/envato-market.zip)

**Comment by Evelyn7** [comment]
@dtbaker, are you now saying that you Have Updated the envato-market plugin? Because just 2 days ago via another thread on this forum I was told it was Not Updated... Please verify. Thanks!

**Comment by dtbaker** [comment]
The zip file above is a "test" for the next version. You are welcome to test this updated version, or you are welcome to wait a few more days for the official release. Up to you.

**Comment by Evelyn7** [comment]
I would prefer to wait for the official release. Please let me know when that is out. Thanks!

**Comment by Evelyn7** [comment]
Hello+
I believe I just received the Official Notice of the new Envato Market Plugin v. 2.0 from you... So, I went to one of my websites and saw that it had an "update" option (under Plugins) - I clicked this and it said "update failed"... Please advise.

**Comment by Evelyn7** [comment]
Aww... SNAP! I jumped the gun - I made another attempt to update via Dashboard > Updates and that worked! Thanks!

**Comment by Evelyn7** [comment]
Hey! The 2.0 actually works! It DOES update everything as expected - yay! Thank you very much for fixing this plugin!!!!!!!
