### ISSUE TITLE
update doesn't work

### ISSUE THREAD

**Issue by ChDUP** [envato/wp-envato-market#110]
Hi
When I clic on "update available" for my theme, I just have a js error in the console.
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.b.envato.updateTheme (updates.min.js?ver=1.0.0-RC2:1)
    at HTMLAnchorElement.<anonymous> (updates.min.js?ver=1.0.0-RC2:1)
    at HTMLDivElement.dispatch (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.8:3)
    at HTMLDivElement.r.handle (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.8:3)
```

**Comment by Paulsky** [comment]
I had/have the same issue and error's. I right clicked on the 'update available' link, and opend the link in a new tab. I then waited for it to finish loading, and the theme became updated! Hopefully someone finds this workaround useful.

**Comment by Evelyn7** [comment]
Hi, @Paulsky+
Thank you for this work-around! It worked for me! I had the same issue, but I never received any error messages as @ChDUP shows above, so started another thread on this same topic... No one responded to that thread, but I will post a link to this one there just in case others are following it.
+ES

**Comment by Paulsky** [comment]
@Evelyn7, happy to hear that the word-around worked for you! Are you sure you didn't have any (Javascript) error's in your console?

For the record.  I'm using Wordpress 4.8, PHP 7.0 and the latest version of this plug-in.

**Comment by Evelyn7** [comment]
Hi+
No I had no error codes - I would click on the "update available" link provided via the Envato Market Plugin and it would not do anything (not even a "wait" symbol). I manage other sites & use the Envato plugin on all of them (same plugin version) and did not have any issues on any of them. Yes, my WP & this plugin are on the latest versions - so don't know why this issue happened. Each site has a different Theme. I did reach out to this Theme's Author but they could not provide any assistance/guidance on the Envato Market Plugin.
Thanks!!

**Comment by m-t-dwyer** [comment]
Hi +, 
I am still having this issue and getting the following error:

`TypeError: undefined is not an object (evaluating 'b.envato.l10n.updatingLabel.replace')
updateThemeupdates.min.js:1:2309 (anonymous function)
updates.min.js:1:7884
dispatchload-scripts.php:2:12449
handleload-scripts.php:2:9178`

@Evelyn7 Your workaround did not work for me, I am able to follow the link, but it results in a "No updates available for this theme" message, when there are definitely updates available.

**Comment by Evelyn7** [comment]
Hi, @m-t-dwyer 

Sorry to hear that it did not work for you! I am not the author of this plugin and do not have any other suggestions on how to get it to work. I do not know why the link I posted to my individual thread is not showing/working on this thread.

I do advise you to submit your own ticket on this plugin support forum about your specific issue and see if you get a response from the plugin author (or anyone else)...

**Comment by m-t-dwyer** [comment]
@Evelyn7  Thanks for the reply. I'm fine with FTP'ing updates for now, just wanted to add my experience for the developers reference here when they're working on a fix.  Thanks!

**Comment by tarek009187** [comment]
same problem with me as well.
is there going to be any fix shortly?

**Comment by ksere** [comment]
Also came across this JS error on a site. 
Clicking 'Update' on the theme under 'Appearance > Themes' worked for me.

**Comment by byronyasgur** [comment]
I run a number of sites and see it on some sites but not on others. I wonder is the theme the connecting factor. So far I've seen it not work on 2 site with very old versions of separate themes from Kriesi

**Comment by dtbaker** [comment]
Hey @byronyasgur , @ksere , @tarek009187 , @m-t-dwyer , @Paulsky , @ChDUP  you are welcome to test the new version of the plugin.

Please delete the old `Envato Market` plugin from your WordPress installation and then add this attached plugin ZIP: 
[envato-market.zip](https://github.com/envato/wp-envato-market/files/1782074/envato-market.zip)

**Comment by byronyasgur** [comment]
@dtbaker tried that - got error - Update Failed: Update package not available

**Comment by dtbaker** [comment]
Thanks @byronyasgur - I'd love to work with you to resolve this issue, please send through an email to dtbaker@gmail.com and I can help find out what the cause of this issue is.

**Comment by byronyasgur** [comment]
Is there any news on this? Did you get my emails?

**Comment by dsgolfside** [comment]
i'm getting this error : Update Failed: Update package not available.    if i go to the envator plugin admin screen it says there is an update available but then says i have the latest version when i try to update ..... can you help please?
![screen shot 2018-05-04 at 4 44 31 pm](https://user-images.githubusercontent.com/17970682/39652121-82de7756-4fba-11e8-85c4-996c8f4fd12b.png)
![screen shot 2018-05-04 at 4 44 15 pm](https://user-images.githubusercontent.com/17970682/39652122-82f643d6-4fba-11e8-9afb-401e7282dcfe.png)
