### ISSUE TITLE
Can't update theme. It shows "Update Failed: Download failed. cURL error 35: error:....."

### ISSUE THREAD

**Issue by kanatk** [envato/wp-envato-market#113]
After I update a theme "Listing Pro", it display an error "Update Failed: Download failed. cURL error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure"  ( screenshot http://imgur.com/XywBReK )

I tried to update other theme, e.g. Twenty Fourteen, Twenty Fifteen but it works fine http://imgur.com/iqB9MSc

I have contacted my server company, they said the cURL is already activated an there's no problem. So I contacted the theme creator ( https://themeforest.net/item/listingpro-multipurpose-directory-theme/19386460 ) But he said it's not a problem on their side and it is an auto update plugin issue.

Why it shows error? And how to fix this?

**Comment by JosKlever** [comment]
See this ticket: https://github.com/envato/wp-envato-market/issues/104

**Comment by dtbaker** [comment]
Hey all, we've changed API edge providers so please let us know if any new SSL related issues appear. Closing now.
