### ISSUE TITLE
update doesn't work

### ISSUE THREAD

**Issue by Ange91** [envato/wp-envato-market#114]
Hi, every time I click on "update available" it doesn't do anything, it is written "update in progress" (see attached file) but even after a long time (2 hours) nothing happens. Is there something to do to make it work ?
Thanks
![update](https://user-images.githubusercontent.com/29748017/27624464-24c01314-5be1-11e7-8a98-d5e4ab07ee97.JPG)

**Comment by vshamraeva** [comment]
Same problem
PLEASE HELP SOMEBODY! :-)

**Comment by wpsos911** [comment]
Same problem. Please, help.

**Comment by IPIlaurens** [comment]
![o8ihax3](https://user-images.githubusercontent.com/29164363/28266256-258363c4-6af4-11e7-91dc-ca2306c34f5f.png)

**Comment by imth3walrus** [comment]
Has anybody been able to figure this out?

**Comment by jrgraphicdesign** [comment]
Having the same issue.

**Comment by advantechsoftware** [comment]
Same problem here. Hasn't worked in a while.

![image](https://user-images.githubusercontent.com/25445514/28508307-6e9a12e0-707d-11e7-8df1-78bab31ddfcf.png)

**Comment by LB79** [comment]
Also having this problem. Deleting the plugin and reinstalling does nothing to help. Also, right click>open in new tab tells me that my theme is the latest version which is isn't. 
Any idea when this will be fixed? Thanks

**Comment by osterman** [comment]
Same problem... but in addition to that, getting a cross-domain scripting error.

![image](https://user-images.githubusercontent.com/52489/29195485-9866ae08-7de3-11e7-8b53-faa1979e69d2.png)

**Comment by mpandzo** [comment]
As a quick fix I commented out lines 153 and 304

    153: // $message.attr( 'aria-label', wp.envato.l10n.updatingLabel.replace( '%s', name ) );

    304: // $message.attr( 'aria-label', wp.envato.l10n.updateFailedLabel.replace( '%s', name ) );

**Comment by th3gman** [comment]
Same issue here as well, unable to update any themes.

**Comment by swinggraphics** [comment]
I get this error in the console:
TypeError: b.envato.l10n.updatingLabel is undefined  updates.min.js:1:2262

**Comment by aero2graph** [comment]
Not working.
"The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions."

**Comment by flamingtop** [comment]
As @mpandzo pointed out, I modifed updates.min.js and replaced all those wp.envato.l10n.updatingLabel.replace( '%s', name ) occurances to '', and the plugin starts to work fine.

**Comment by dtbaker** [comment]
Fixed
