### ISSUE TITLE
Registering token for wordpress plugin - Item ID?

### ISSUE THREAD

**Issue by Herzogdb** [envato/wp-envato-market#115]
When registering this plugin on wordpress, the instructions say to click the link to generate the key. Once I have and enter the key, it also asks for an Item ID. Where does this come from?

Also, will this allow themes to automatically get updated through Envato instead of the usual downloading of the zip and re-installing manually every time?

**Comment by TheArtBeacon** [comment]
Has anyone figured this out? I'm having the same trouble. I can find the token but a pop up requires that I reenter the token and enter an item ID. Where do I find the item ID?

**Comment by JosKlever** [comment]
The Item ID can be found in the license file or in the url of the product you want to activate. Most of the time its a 8-digit number.

**Comment by dtbaker** [comment]
We recommend you use the first option on the page (Global token) rather than the individual Item ID setting. It's much easier to use.
