### ISSUE TITLE
The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

### ISSUE THREAD

**Issue by Sashunator** [envato/wp-envato-market#117]
Hello! I recieve this kind of error, when I try to udpate the theme.

I have downloaded plugin here https://envato.github.io/wp-envato-market/dist/envato-market.zip
![error plugin](https://user-images.githubusercontent.com/31207909/29515833-b86e49ea-8676-11e7-8ddf-84f71ab892d2.jpg)

**Comment by dtbaker** [comment]
We have a fix for this coming out in the next few days.

**Comment by Sashunator** [comment]
Hello! Do you fix it already? Should I download it again? Or I can update it automatically? 12.03.2018, 02:25, "dtbaker" <notifications@github.com>:We have a fix for this coming out in the next few days.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- С уважением, Кудинов Александр, администратор клуба путешественников "Миры" (www.club-miry.ru), +7 495 517 27 57.
