### ISSUE TITLE
Got JS Error: cannot read property of "replace" of undefined on clicking "update available link"

### ISSUE THREAD

**Issue by flamingtop** [envato/wp-envato-market#118]
Wordpress version: 4.8.1
Envato market version: 1.0.0-RC2
Screenshot: https://www.screencast.com/t/lTtCyZJ8lKes

**Comment by joeldesmit** [comment]
Having this error too.
<img width="935" alt="screen shot 2017-08-25 at 12 30 59" src="https://user-images.githubusercontent.com/6246345/29710594-4d64a676-8991-11e7-90d1-91e57febce7d.png">

**Comment by wowthemes** [comment]
Getting the same error. Trying this plugin on localhost, is there an issue working on localhost?
![envato-market](https://user-images.githubusercontent.com/16266732/29809117-4ce945aa-8cb4-11e7-813f-b9259c49d4d9.png)

**Comment by widoz** [comment]
Hi there,

Seems some l10n strings properties are no longer available.

I found these  `wp.envato.l10n.updatingLabel`, `wp.envato.l10n.updateFailedLabel` and `wp.envato.l10n.updatedLabel`. 

Changed to `wp.envato.l10n.updating`, `wp.envato.l10n.updateFailed` and `wp.envato.l10n.updatedMsg` respectively and the update gone as usual.

Don't know if there are other strings, need more time to check them.

**Comment by pablodesogos** [comment]
@widoz Thank you so much! 
You're totally right: those l10n strings keys have changed. I've replaced them in the update.js (and it's minified version) and everything works fine now.

So, for anyone facing this issue, just replace all ocurrences of this keys with the ones that Widoz mentioned:

updatingLabel => updating
updateFailedLabel => updateFailed
updatedLabel => updatedMsg
 

In the update.js and update.min.js files located under the evanto-market/js folder

**Comment by KeesCBakker** [comment]
You can use the following workaround to update your theme without modifying JS on the server:
- Open the JavaScript console (F12)
- Paste the following line in the console and press enter:<br/> `window.wp.envato.l10n.updatingLabel = window.wp.envato.l10n.update`
- Click on the update button
- After the update is finished, another error will be shown
- Hit F5 - your theme has been updated

**Comment by brubrant** [comment]
Thanks @KeesCBakker , this workaround worked for me.

**Comment by dtbaker** [comment]
Fixed.
