### ISSUE TITLE
OAuth Personal Token could not be verified

### ISSUE THREAD

**Issue by ossigeno** [envato/wp-envato-market#119]
1. The Personal Token has every possible permission. 
2. It is so painful to upgrade a theme using this plugin. Silent failures or error messages not related to the issue as in 1. above.
3. Will it ever come off beta RC2?
4. How can Envato rely on this buggy software? It is a hindrance to upgrading themes. It puts me off buying any theme that relies on it.

**Comment by dtbaker** [comment]
Hey @ossigeno we're picking this up again now and we should move it out of RC soon.

If you are still having personal token issues please let us know and we can look into it further.
