### ISSUE TITLE
Javascript error on clicking 'Update Available' with WordPress 4.8.1

### ISSUE THREAD

**Issue by ossigeno** [envato/wp-envato-market#120]
This plugin doesn't work on WordPress 4.8.1?

There is a Javascript error on clicking 'Update Available' on the theme tab:

updates.min.js?ver=1.0.0-RC2:1 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.b.envato.updateTheme (updates.min.js?ver=1.0.0-RC2:1)
    at HTMLAnchorElement.<anonymous> (updates.min.js?ver=1.0.0-RC2:1)
    at HTMLDivElement.dispatch (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.8.1:3)
    at HTMLDivElement.r.handle (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.8.1:3)

**Comment by valendesigns** [comment]
Thanks for reporting the issue. I'm going to be making updates and fixing bugs this weekend and next week. I'm aiming to have a new stable version coming mid September.

**Comment by Evelyn7** [comment]
Hello, @valendesigns!

You are the first Plugin Author to respond to any issue that I have seen! I placed a ticket months ago about this plugin not updating anything and received no response. I've been following several other tickets on this forum and none of them have received any responses from any Plugin Authors.

I am so glad to see that YOU are still working on this plugin!! Please let us all know when this plugin will work again! Thank you!

**Comment by widoz** [comment]
I think it's related to the #118

**Comment by danyj** [comment]
Looks like this commit has never been included and no one can actually use this plugin to update anything. Just list the purchases. Is this project dead?

**Comment by mensmaximus** [comment]
All you can do is sending tweets to @envato_help on twitter. every day

**Comment by ossigeno** [comment]
Envato don't listen, have contacted them several times since last September. I think better approach is to contact sellers on Envato who has products that depend on this plugin and explain love to buy your product but should you issue any upgrades I won't be able to because of this dependency.

**Comment by Evelyn7** [comment]
Agreed! @ossigeno has the right idea! I have given up on this Forum and am telling each Theme Author for every theme I have purchased via Envato/Themeforest that I cannot use the required Envato Plugin to update their theme. Each has come back with a different response. If everyone does this, then the Theme Authors will (eventually) talk to Envato about it... Please contact your Theme Author about this plugin not working with their theme!

**Comment by danyj** [comment]
From theme reviewer we were instructed no to use our update script 

"Theme updates should be handled via ThemeForest marketplace only"

and were referred to this plugin. Now we cant use it and even if we fix the bugs ourselves the future of this plugin is grim so I am very reluctant to include this as our theme requirement. 

So if this one is depreciated 
https://github.com/envato/envato-wordpress-toolkit

and current "recommended" does not work , what do we do now?

**Comment by danyj** [comment]
I opened a new issue here to get clarification https://github.com/envato/wp-envato-market/issues/137

**Comment by dtbaker** [comment]
Fixed.

**Comment by danyj** [comment]
@dtbaker   

> fixed 

where is the commit?  nothing changed in the git .

**Comment by dtbaker** [comment]
Develop branch, new version release soon. Thanks for waiting
