### ISSUE TITLE
Installed toolkit but visual composer still hasn't updated

### ISSUE THREAD

**Issue by OnliFia** [envato/wp-envato-market#121]
Hello,

I've installed this plugin onto my wordpress but visual composer still hasn't updated and neither has slider revolution.

Is there any reasons why or any time scale to when this will happen?

Thanks

**Comment by garymgordon** [comment]
I'm having a similar issue that was noted in another issue posting at  https://github.com/envato/wp-envato-market/issues/105.  I'd also like to know if this is a related issue.

**Comment by dtbaker** [comment]
We have a fix for this coming out in the next few days.
