### ISSUE TITLE
Update Link not clickable anymore.

### ISSUE THREAD

**Issue by freddystreet** [envato/wp-envato-market#124]
Hi there,
i dont know if this problem was already solved but this plugin worked fine for me until
WP 4.8. i think. Now when i want to do the update it just doesnt do anything when i click on "Update Available".
Im running it on 2 different websites and on the other one its not a problem.

im not experienced at coding so if there is a solution to this problem can maybe someone tell me step
by step what to do?

My Token is completely authorized and working by the way (2 green checkmarks)
so this cant be the problem.

Thanks in advance.
Frederik

**Comment by JosKlever** [comment]
Try to update via Dashboard - Updates or Appearance - Themes and see what that does.

**Comment by freddystreet** [comment]
IT WORKED hahaha.

Thanks my friend. Saved me a lot of grey hair!!

much appreciated.

Cheers  from Berlin - Freddy

**Comment by dtbaker** [comment]
Fixed in latest version, update coming soon.
