### ISSUE TITLE
"The item cannot be downloaded." when adding a new item

### ISSUE THREAD

**Issue by jeremiahbenes** [envato/wp-envato-market#125]
Hi, 
I have downloaded and installed this plugin but whenever I attempted to add the [Brooklyn theme](https://themeforest.net/item/bridge-creative-multipurpose-wordpress-theme/7315054) to receive updates, I get an error that states "The item cannot be downloaded".

For reference, I am running the latest version of the plugin on WordPress 4.8.3. Please advise.

**Comment by dtbaker** [comment]
Hey @jeremiahbenes please reach out to me if this is still an issue and I can help solve the problem. I may need temporary access to your testing site so I can see, re-produce and fix the issue promptly. Thanks.
