### ISSUE TITLE
update should override theme instead of uninstalling and reinstalling

### ISSUE THREAD

**Issue by larsschellhas** [envato/wp-envato-market#127]
files added in a theme folder (like custom.css) are deleted, which does not make any sense.
Please change this behaviour

**Comment by purethemes** [comment]
This is how themes are updated even from official WordPress.org repository. Use child theme to avoid that problem.

**Comment by dtbaker** [comment]
Thanks @purethemes - yes closing this issue as it's how the official update process happens. The theme should be coded correctly to regenerate static assets after an update, or a child theme should be used if the css changes were applied manually outside of theme settings area.
