### ISSUE TITLE
User-based API Key

### ISSUE THREAD

**Issue by JoeHana** [envato/wp-envato-market#128]
Especially when it comes to putting a website together for a customer it makes not much sense to disclose all the various available themes and plugins through the Envato Market Plugin to every admin. So it might be better to attach the API Key to the User in WP and only allow access to those admins with a valid API Key entered in the profile.

**Comment by dtbaker** [comment]
Hey @JoeHana 

I believe you can do this through the single use token feature here:

![image](https://user-images.githubusercontent.com/543073/36657963-5886ba92-1b1a-11e8-8b40-c937b9b99207.png)


Simply enter your personal token along with the item ID and the user will not be presented with all the other available themes from your account, only the item ID you specify. 

Thanks.
