### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by roltur** [envato/wp-envato-market#129]
Referring to #116 : I get the following warning on the dashboard of one of our sites:

 `Warning: Invalid argument supplied for foreach() in /nas/content/live/sitename/wp-content/plugins/envato-market/inc/api.php on line 320
`

I've tried creating a fresh token, which changes nothing. The plugin works just fine, but some of my colleagues always come running to me asking if there is something wrong with the site.

We run 4 pages that have literally the same setup, plugins, WordPress 4.9, theme, everything. Yet this message pops up at only one of these sites. Any ideas? :)

**Comment by manouallou** [comment]
I am facing the same problem / warning too. 
Is there an official response from the Envato plugin authors?

**Comment by roltur** [comment]
I recently found that this issue also causes a WP All Import Pro to fail. I get the following message

`Warning: Invalid argument supplied for eacH() in /.../wp-content/plugins/envato-market/inc/api.php on line 320 {"imported":1,"created":"o","uploaded":1,"skipped":"0","percentage:"0,"warnings":0,"errors":0,"log":"`

Looks like I'm might have to disable/delete the Envato Market plugin on this site to avoid it crashing my other plugins. Hope you guys at Envato can take a look at this issue.

**Comment by fritjg** [comment]
Same...

**Comment by mensmaximus** [comment]
If everybody would send tweets to @envato_help on twitter every day we might get this sorted out

**Comment by dtbaker** [comment]
Thanks. Fixed.

**Comment by design2dev** [comment]
i still get this error. how do i fix it?

**Comment by dtbaker** [comment]
The update is going to be released shortly.
