### ISSUE TITLE
Themes and Plugins don't display properly

### ISSUE THREAD

**Issue by brandlinedigital** [envato/wp-envato-market#130]
Since the recent WP update or maybe the previous update, Envato Market plugin started to act weird. Here are some screenshots.

https://cl.ly/3n0p2I1O232G
https://cl.ly/1a112w372G0j

**Comment by danfisher85** [comment]
@brandlinedigital that's because Envato API endpoints has been changed https://forums.envato.com/t/changes-to-buyer-list-purchases-envato-api-endpoint/142112

**Comment by mensmaximus** [comment]
If everybody would send tweets to @envato_help on twitter every day we might get this sorted out

**Comment by dtbaker** [comment]
Fixed

![image](https://user-images.githubusercontent.com/543073/36657772-9dc1d070-1b19-11e8-94f6-c2fb5fa84bc3.png)
