### ISSUE TITLE
Envato market plugin not working ?

### ISSUE THREAD

**Issue by DevFaik** [envato/wp-envato-market#131]
Hi ,
envato market plugin not working ???
![2017-12-23_17-20-28_5945](https://user-images.githubusercontent.com/25863097/34417118-accafbc8-ebee-11e7-902e-7fddf271ef02.png)
before update envato update theme not working???

**Comment by brinny37076** [comment]
I am wondering the same thing, and there doesn't seem to be anyone monitoring these questions. This plugin is causing a 504 error on one of my sites and apparently a lot of others are also having multiple issues. Is this project dead?

**Comment by dtbaker** [comment]
We're releasing an update shortly. Stay tuned!
