### ISSUE TITLE
Token and item number are not registering to install latest version of the template 

### ISSUE THREAD

**Issue by Taylormade27** [envato/wp-envato-market#132]
Token and item number are not registering to install latest version of the template 

Token generated
Item Number taken from notes for LOUD Theme.

**Comment by dtbaker** [comment]
Hey @Taylormade27 you are welcome to test the new version of the plugin.

Please delete the old `Envato Market` plugin from your WordPress installation and then add this attached plugin ZIP: 
[envato-market.zip](https://github.com/envato/wp-envato-market/files/1782074/envato-market.zip)
