### ISSUE TITLE
new purchased plugin not showing

### ISSUE THREAD

**Issue by dsgolfside** [envato/wp-envato-market#134]
hello for some reason a plugin i just purchased is not showing up under the plugins tab i've refreshed , cleared cache, deactivated plugin etc any ideas on how to fix?

**Comment by dtbaker** [comment]
Hey @dsgolfside you are welcome to test the new version of the plugin.

Please delete the old `Envato Market` plugin from your WordPress installation and then add this attached plugin ZIP: 
[envato-market.zip](https://github.com/envato/wp-envato-market/files/1782074/envato-market.zip)
