### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by danyj** [envato/wp-envato-market#137]
We were instructed by  theme reviewer  not to use our update script 

"Theme updates should be handled via ThemeForest marketplace only"

and were referred to this plugin. Now we cant use it and even if we fix the bugs ourselves the future of this plugin is grim so I am very reluctant to include this as our theme requirement. 

So if this one is depreciated 
https://github.com/envato/envato-wordpress-toolkit

and current "recommended" does not work , what do we do now?

**Comment by Evelyn7** [comment]
Thank you, @danyj, this clarifies the issue quite well! I look forward to seeing the plugin author's response!

**Comment by johndoegithub** [comment]
In our company, we rely on some Codecanyon plugins to run our site. We would like this project to be continued so that plugins can be updated regularly, which is a very recommended security practice.

**Comment by flexbarker** [comment]
bump.

**Comment by danyj** [comment]
@flexbarker  I say no need for bump , if we did not get reply by now it is obvious.

**Comment by mensmaximus** [comment]
I have started to tweet each new request for the envato market plugin to @envato_help @envato @collis. Lets see how long it will take to make them aware about the obvious problem with the official envato market plugin.

**Comment by worthdesigning** [comment]
The plugin doesn't work for me. Following with interest.

**Comment by dtbaker** [comment]
Jumping in to sort all this out now. Update coming shortly. Thank you for your patience.

**Comment by flexbarker** [comment]
nice

**Comment by flexbarker** [comment]
nice.
