### ISSUE TITLE
Problems with woocommerce single product page

### ISSUE THREAD

**Issue by lendrastudio** [envato/wp-envato-market#139]
Hi, I´m having an issue with the woocommerce single product page. Seems to be right when is in desktop view, but in the mobile the product image align to left and resizes to small pic while the content align to the right. In the demo page is no happening this.

**Comment by AaronRutley** [comment]
Hi @lendrastudio I don't think that's related to the Envato Market Plugin, it might be best that you contact the author of your theme for support?
