### ISSUE TITLE
iframe for version details is empty cause of X-Frame-Options = 'SAMEORIGIN'

### ISSUE THREAD

**Issue by revaxarts** [envato/wp-envato-market#14]
Checking the version details get refused cause of the same origin policy Envato set on their market:

```
Refused to display 'http://themeforest.net/user/[USERNAME]/portfolio' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

In general this shouldn't end on the user profile page rather on a dedicate change log page of the item.
This is of course only Envato can introduce. If they want to keep the policy (which is legit) they should exclude this rule from the change log page.

**Comment by valendesigns** [comment]
There really is nothing the plugin can do in this situation from a development standpoint. However, I'll leave the issue open for posterity and hopefully someone at Envato will take notice.

**Comment by dtbaker** [comment]
Has there been any word on a dedicated change log area for Envato items? http://themeforest.net/forums/thread/envato-can-you-create-a-changelog-tab-for-our-items-/130853?page=2&message_id=1041807#1041807
