### ISSUE TITLE
"Warning: Illegal string offset" in Worpdpress backend

### ISSUE THREAD

**Issue by Cri85** [envato/wp-envato-market#140]
Hello everyone, I get this error in my backend, in my local installation, in the themes and plugin option of Envato Market Plugin for Wordpress, in the rating section. In some of plugin I have it appears, check the image to see one of them

Warning: Illegal string offset 'count' in C:\xampp\htdocs\INSERTNAMEHERE\wp-content\plugins\envato-market\inc\admin\functions.php on line 394

Warning: Illegal string offset 'count' in C:\xampp\htdocs\INSERTNAMEHERE\wp-content\plugins\envato-market\inc\admin\functions.php on line 395

This is the line 394 and 395

`<?php wp_star_rating( array( 'rating' => ( $plugin['rating']['rating'] / 5 * 100 ), 'type' => 'percent', 'number' => $plugin['rating']['count'] ) ); ?>`

`<span class="num-ratings">(<?php echo esc_html( number_format_i18n( $plugin['rating']['count'] ) ); ?>)</span>`

Warning: number_format() expects parameter 1 to be float, string given in C:\xampp\htdocs\INSERTNAMEHERE\wp-includes\functions.php on line 221

 And 221

`$formatted = number_format( $number, absint( $decimals ), $wp_locale->number_format['decimal_point'], $wp_locale->number_format['thousands_sep'] );`

I run latest XAMPP version with php7.

![error envato](https://user-images.githubusercontent.com/36699482/36482366-5e3eb6ac-1713-11e8-8fab-76b3a18d8033.jpg)

**Comment by garciacrew** [comment]
same here.

**Comment by dtbaker** [comment]
Fixed.
