### ISSUE TITLE
Plugin NOT Updating Files as Expected

### ISSUE THREAD

**Issue by Evelyn7** [envato/wp-envato-market#142]
Hi+
I downloaded the zip file from your website on 02/26/18, then removed the old plugin and installed the new zip file via the back-end Plugins > add new > upload. I then activated - and it still did not work. It did show an "update" button/link, however, when I clicked that nothing happened.

WP v 4.9.4
Envato Plugin v. 1.0.0-RC2

So, is the zip file on your website the "new" (fixed) version of the plugin? If so, why is it not working as expected? If not, where do I find the correct version?
Thanks!

**Comment by dtbaker** [comment]
Hi @Evelyn7  the fixed version is not available to download yet, I will post back here once the fixes are released. Hopefully today.

**Comment by Evelyn7** [comment]
Hi, @dtbaker 

Thank you for the quick response! I will keep an eye out for your post...

**Comment by Snowadler** [comment]
Same Here :(  it Says Update Available - put i allready purchased the item ?
<img width="572" alt="bildschirmfoto 2018-03-05 um 10 48 08" src="https://user-images.githubusercontent.com/13508155/36968451-d293a8ca-2062-11e8-9b80-17b99d82028f.png">

**Comment by dtbaker** [comment]
Hey @Evelyn7 and @Snowadler you are welcome to test this copy of the plugin.

Please delete the old `Envato Market` plugin from your WordPress installation and then add this attached plugin ZIP: 
[envato-market.zip](https://github.com/envato/wp-envato-market/files/1782074/envato-market.zip)

**Comment by Evelyn7** [comment]
@dtbaker, This just came in - please disregard my  question on the other thread... I will test and get back with you on this thread! Thank you!

**Comment by Evelyn7** [comment]
I would prefer to wait for the official release. Please let me know when that is out. Thanks! +ES
