### ISSUE TITLE
Item can't found in single and global OAuth

### ISSUE THREAD

**Issue by uponity** [envato/wp-envato-market#145]
Hello,

i purchased a new Item from CodeCanyon on 03-05-2018.

If i add my oAuth Code for Global OAuth Code, i can see all my purchased Items. But not the newest.

If i try the single OAuth i get an Error with "The Token or Item ID is incorrect." 

Regards,
Danny

**Comment by dtbaker** [comment]
We have a fix for this coming out next week. Thanks.

**Comment by sebastianjacobs** [comment]
I've the same problem with Version 2.0.0

"Your OAuth Personal Token has been verified. However, there are no WordPress downloadable items in your account."

Item I've bought: https://codecanyon.net/item/groups-file-access-wordpress-plugin/2228793
and installed.
