### ISSUE TITLE
This Forum is Emailing Me Every Comment - How to Stop That?

### ISSUE THREAD

**Issue by Evelyn7** [envato/wp-envato-market#146]
Hello+

I have asked several questions via this forum regarding the Envato Market Plugin. I have received the emailed responses for those.... And, every single question and response that has ever been posted on this forum since I asked my own questions. This is very frustrating and comes across as spam since I did not sign up for this forum to email me everything - only for it to email me on my own question threads.

I cannot mark those emails as "spam" since my email system will mark all emails from this form (including any question threads I create) and I still want to get the emails on my threads.

Going into each individual question thread and "unsubscribing" is time consuming and does not prevent future question threads from being emailed to me. 

Please tell me where to go to stop this forum from emailing me EVERYTHING and to only email me on my own question threads. 

Thank you.

**Comment by dtbaker** [comment]
You can try here: https://github.com/notifications/participating or here: https://github.com/watching or here: https://github.com/settings/notifications

**Comment by Evelyn7** [comment]
Hello+

Thank you for the quick response and links. Please advise exactly which settings I should check to receive emails ONLY for the threads I have started or participated in, not all emails....

Thanks!

**Comment by Evelyn7** [comment]
If I "unwatch" "envato/wp-envato-market" then will I no longer receive emails for the threads I started and/or participated in?

**Comment by dtbaker** [comment]
Unwatching would be the best action here.

**Comment by Evelyn7** [comment]
Thank you.
