### ISSUE TITLE
Test own item

### ISSUE THREAD

**Issue by ktmn** [envato/wp-envato-market#151]
I know this has been raised before and not really related to the plugin, but could there be any way for the Envato API to not only return items that you've purchased, but also items that you have created, so that it would be possible to test your own item's update functionality. Specially if it's custom like in the @dtbaker's setup wizard.

**Comment by dtbaker** [comment]
Unfortunately this isn't possible right now. We're looking at ways to allow better testing around an authors own items and will update the community when it's ready. There is no ETA at this stage.
