### ISSUE TITLE
Can't find my last purchased Plugin from codecanyon

### ISSUE THREAD

**Issue by uponity** [envato/wp-envato-market#152]
Hello,

i have the Same issue like with version 1 of the plugin.

If i create my token and insert it in the Token field, i can see all my purchased themes and plugins.
But not my last purchased from codecanyon.

If i insert the token and the item id, i become the error "The Token or Item ID is incorrect."

**Comment by dtbaker** [comment]
Hi @uponity I'd love to help out with this more and find out the reason this isn't working. 

Are you able to submit a support ticket here: https://help.market.envato.com/hc/en-us/requests/new ?

Please create a new token for me to test and send it in the support ticket. You are welcome to reply here with the support ticket ID number once it has been submitted. 

THanks.

**Comment by uponity** [comment]
Thank You for your Response. Ticket ID: 1065859

Regards
