### ISSUE TITLE
Plugins list not complete

### ISSUE THREAD

**Issue by markbond1007** [envato/wp-envato-market#153]
I have entered a token, the themes list seems fine, however the plugins list isn't complete (there are at least 3 in my list not showing). It doesnt appear to be as simple as the last item (or items) as 1 is in between others that are showing.

**Comment by dtbaker** [comment]
Hi @markbond1007  I'd love to help out with this more and find out the reason this isn't working. 

Are you able to submit a support ticket here: https://help.market.envato.com/hc/en-us/requests/new ?

Please create a new token for me to test and send it in the support ticket. You are welcome to reply here with the support ticket ID number once it has been submitted. 

THanks.
