### ISSUE TITLE
Nothing loads in Settings/Setup page

### ISSUE THREAD

**Issue by ericaeide** [envato/wp-envato-market#154]
Nothing is loading on the settings page.
![envato market touch of home furnishings minnesota wordpress](https://user-images.githubusercontent.com/1738820/37489837-e254e6f0-2866-11e8-821e-098b4d4548d6.png)

**Comment by dtbaker** [comment]
Hi @ericaeide, 

Can I please ask what version of PHP you are running?

If you would like to contact me I can login to your website and help diagnose the issue.

Thanks,
dtbaker

**Comment by ericaeide** [comment]
Hi @dtbaker, thanks for your reply. Looks like that site is running PHP 5.6.34, is that too low?

**Comment by ericaeide** [comment]
I've updated PHP version to 7.1, no difference.

**Comment by dtbaker** [comment]
Thank you for testing the PHP version @ericaeide 

Very interesting issue! If you would like to take this further please submit a support ticket and we can discuss further. This will likely involve obtaining some temporary FTP and WordPress login details so we can debug the issue on your website and provide a fix. A private support ticket can be sent here: https://help.market.envato.com/hc/en-us/requests/new 

Let me know the support ticket ID number so I can jump on to answer.

Thanks,
dtbaker
