### ISSUE TITLE
Salient Theme can't update

### ISSUE THREAD

**Issue by carnate69** [envato/wp-envato-market#155]
We have added in our token to update the salient theme, it shows up in our themes list just fine, but I don't see anywhere to actually update the theme or make the envato market plugin do anything.  Are we missing something here?  It seems maybe the red bar is blocking our click?

![salient](https://user-images.githubusercontent.com/37451869/37533678-e110cdce-2918-11e8-9f95-7cf7df5f554d.jpg)

**Comment by JosKlever** [comment]
Check Appearance - Themes or Dashboard - Updates to install this update.

**Comment by carnate69** [comment]
We tried this but it says that we have the latest version installed.  I think the newest is 3.5.5 and we are on 3.5.3

On Mar 16, 2018, at 12:55 PM, Jos Klever <notifications@github.com<mailto:notifications@github.com>> wrote:


Check Appearance - Themes or Dashboard - Updates to install this update.

**Comment by carnate69** [comment]
It actually updated by going to dashboard > updates, but error ed out in appearance > themes, we'll keep an eye on it, thanks!
________________________________

**Comment by carnate69** [comment]
The first change I noticed on our test site is that the update cleared all of our Custom CSS we changed within our Additional CSS Sectiopn in Wordpress, is this something that you generally back up before updating into notepad?

Not to get too into it, but what other settings can we expect to be cleared out when we do these updates?  We're on our first wordpress site!
________________________________

**Comment by dtbaker** [comment]
Hi @carnate69 these settings should not be cleared each time you update. It sounds like there may be something wrong with the salient theme. I'll have a look into why this is happening and report back.

**Comment by carnate69** [comment]
Any update on this?
________________________________

**Comment by dtbaker** [comment]
We are releasing version 2.0.1 of the market plugin shortly. This should solve some issues or at least give a more detailed error message.

If the problem persists please contact the Salient theme author and let them know you are having trouble using the Envato Market WordPress plugin.
