### ISSUE TITLE
Theme ratings are not displayed

### ISSUE THREAD

**Issue by danfisher85** [envato/wp-envato-market#158]
For some reason theme ratings are not displayed because  `$theme['rating']['count'] ` is empty (envato-market/inc/admin/functions.php:191)

![screen shot 2018-03-20 at 12 32 43](https://user-images.githubusercontent.com/7786257/37652135-d2e38460-2c3a-11e8-9b42-1359781934de.png)

But it works fine with the following code

`wp_star_rating(array('rating' => $theme['rating']));`

**Comment by AaronRutley** [comment]
@danfisher85 thanks for reporting this, we'll look into it.

**Comment by dtbaker** [comment]
We are releasing version 2.0.1 of the market plugin shortly. This should solve the issue. Thanks @danfisher85
