### ISSUE TITLE
update envato

### ISSUE THREAD

**Issue by Garfield2010** [envato/wp-envato-market#159]
Hello I'm taken over the website. Now I see that the former builder of the website an API code has installed. Now is my question what does envato do for the website. If it is not supported anymore are there things that doesn't work anymore?

**Comment by jacobbednarz** [comment]
Best check out https://build.envato.com/ (which is the API documentation) for what your client is using the API for. My guess would be purchase verification but perhaps also using it to get notifications and download updates for their items.

**Comment by Garfield2010** [comment]
So the plug-ins where I filled in an API uses envato? We have the theme sport by themecanon.



Op 9 apr. 2018 om 00:35 heeft Jacob Bednarz <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Best check out https://build.envato.com/ (which is the API documentation) for what your client is using the API for. My guess would be purchase verification but perhaps also using it to get notifications and download updates for their items.

**Comment by dtbaker** [comment]
In order to receive product updates you will need a valid purchase. If someone else has purchased this product you may not be able to receive those updates. Please contact themecanon for detailed instructions on how to receive product updates.
