### ISSUE TITLE
Allow moving page to a sub menu

### ISSUE THREAD

**Issue by revaxarts** [envato/wp-envato-market#16]
I hate when the admin menu get's to bloated with menu entries. While I agree that the plugin should be in root on activation there should be an option to move it into Tools for instance.

Something like this:

	if($is_sub_menu){
		$page = add_submenu_page( 'tools.php', __( 'Envato Market', 'envato-market' ), __( 'Envato Market', 'envato-market' ), 'manage_options', envato_market()->get_slug(), array( $this, 'render_admin_callback' ) );
	}else{
		$page = add_menu_page( __( 'Envato Market', 'envato-market' ), __( 'Envato Market', 'envato-market' ), 'manage_options', 
	}

**Comment by valendesigns** [comment]
I'll look into adding a filter to move it.

**Comment by valendesigns** [comment]
Moving this is not that simple, there is a decent amount of references to the specific screen location used for redirecting and verifications that must remain that way. Changing this is in involved process and not something I want to do at the moment as it requires touching a lot of code for very little benefit.
