### ISSUE TITLE
API not generating

### ISSUE THREAD

**Issue by cakattack** [envato/wp-envato-market#160]
Hello, I am clicking the link in my wordpress backend "Generate an Envato API Personal Token by clicking this link." and the green dot just blinks and blinks forever and no API key is ever generated. What can I do about this?

**Comment by dtbaker** [comment]
Please try again now, or try a different web browser or computer.

**Comment by cakattack** [comment]
I tried it in chrome, selected every option and am getting this error
message?


​

Caki Cook

Caki Cook Designs | www.cakicookdesigns.com

**Comment by atilladiken** [comment]
I also take the same mistake;

{"error":"unsupported_response_type","error_description":"Unknown response_type parameter passed"}

How can I fix?

**Comment by AngeloG123** [comment]
Same here, also getting this error:
{"error":"unsupported_response_type","error_description":"Unknown response_type parameter passed"}

Any fixes?
