### ISSUE TITLE
Plugin not displayed in items list

### ISSUE THREAD

**Issue by KonstruktStudio** [envato/wp-envato-market#161]
Hello!
We have a [knowledgebase plugin](https://codecanyon.net/item/minervakb-knowledge-base-for-wordpress-with-analytics/19185769) on CodeCanyon, and for some strange reason it is never available for update via Envato Market plugin.
I've checked another plugin, that works well, comapred all meta fields in php header, updated our plugin, but people still can not update it. Is there some additional development / configuration required on our side? Also, how can we test our own products for compatibility? My Token does not allow me to update my own items. Thanks for any info.

**Comment by dtbaker** [comment]
@KonstruktStudio please edit your item on CodeCanyon and submit the `Optional WordPress Plugin` file.

This is the file we install. Without this plugin zip file we cannot provider installation or updates to customers. 

Thanks.
