### ISSUE TITLE
purchased item is not showing in Envato Market’s theme and plugin

### ISSUE THREAD

**Issue by AmirRasheed** [envato/wp-envato-market#164]
as follows purchased item is not showing in Envato Market’s theme and plugin options to update.

https://codecanyon.net/item/stock-manager-advance-invoice-inventory-system/3647040

**Comment by AmirRasheed** [comment]
as follows purchased item is not showing in Envato Market’s theme and plugin options to update.

https://codecanyon.net/item/stock-manager-advance-invoice-inventory-system/3647040

**Comment by AmirRasheed** [comment]
as follows purchased item is not showing in Envato Market’s theme and plugin options/menu to update.

https://codecanyon.net/item/stock-manager-advance-invoice-inventory-system/3647040

**Comment by dtbaker** [comment]
This item is not a WordPress plugin so it cannot be installed in WordPress.
