### ISSUE TITLE
Error deleting Envato WordPress Toolkit (Deprecated)

### ISSUE THREAD

**Issue by tahse** [envato/wp-envato-market#165]
Deactivated Envato WordPress Toolkit (Deprecated).
Attempted to delete and got the following error:

Deletion failed: Internal Server Error

Not helpful!
How do I get past this?

**Comment by dtbaker** [comment]
Please contact the author of the theme from ThemeForest and ask them to assist with "Envato Toolkit" compatibility issues. The purchased theme should work fine with the Envato Toolkit plugin disabled.
