### ISSUE TITLE
envato API - Theme auto update don’t working 

### ISSUE THREAD

**Issue by merlino71** [envato/wp-envato-market#166]
Hello guys!
in a wordpress installation i have the 1.7.1 theme version and despite envato market plugin is perfectly installed and working I see NO upgrade option to the vers. 1.8. (in the envato plugin section)
I’m confused. You can help me to upgrade the theme version automaticalli?

tanks

**Comment by dtbaker** [comment]
Please respond with the name of the theme in question if it is still an issue so we can investigate.
