### ISSUE TITLE
cURL error 6: can not resolve host

### ISSUE THREAD

**Issue by selphet** [envato/wp-envato-market#167]
Hi,

this is actually the complete error:

Download failed. cURL error 6: Could not resolve host: marketplace-downloads.customer.envatousercontent.com

I am hosted on Synthesis, but I don't think the problem is the hosting.  The theme I am using is Salient.

Thx

**Comment by selphet** [comment]
No reply after 2 days????

**Comment by baileyherbert** [comment]
This is not going to be an issue relating to the plugin - it is an issue with the configuration of your web server where CURL cannot perform DNS lookups. I would highly suggest reporting this to your web host.

**Comment by dtbaker** [comment]
Thanks for that @baileyherbert 

Yes @selphet this is an issue with the hosting provider. 

`marketplace-downloads.customer.envatousercontent.com` is with CloudFlare, if your host cannot resolve this domain it either means the host has a very strong firewall or the host has been blocked by CloudFlare for some reason.

Please send this message to the hosting provider and ask them to look at why the plugin is unable to resolve or connect to this domain name.

Best of luck!
