### ISSUE TITLE
wp-envato market installation problem

### ISSUE THREAD

**Issue by naburo** [envato/wp-envato-market#169]
Hello support

I can not install the new version of wp-envato market. The old one is deprecated. 
The error code is:
Envato Market plugin is not installed correctly. Please delete this plugin and get the correct zip file from https://envato.com/market-plugin/.

After installing the plugin again I got the same error code
What is to do?

regards
andreas Wildenhain

**Comment by baileyherbert** [comment]
Can you check inside the plugins directory (default: **`/wp-content/plugins/`**) and verify that the name of the plugin is exactly **`envato-market`**? If it has a different name then you will receive that error.

Basically, the file structure should look like this:

```
wp-content/
├── plugins/
│   ├── envato-market/
│   │   ├── envato-market.php
```

**Comment by dtbaker** [comment]
Please follow the instructions above from @baileyherbert  or the instructions on https://envato.com/market-plugin/
