### ISSUE TITLE
Notice after saving settings

### ISSUE THREAD

**Issue by gthapar** [envato/wp-envato-market#17]
Hi,

I got this notice when I clicked the save button. 
`Notice: Undefined index: previews in /Users/GT/Work/btnsx/wp-content/plugins/envato-market/inc/api.php on line 339`.

I am testing it locally.

Best Regards,
Gautam Thapar

**Comment by valendesigns** [comment]
That seems to be an issue with the item not having a `landscape_preview`. What item is it?

**Comment by gthapar** [comment]
How can I check which item is causing this error?

**Comment by valendesigns** [comment]
@gthapar Create an OAuth token for me to test with and send it to derek@valendesigns.com and I'll take a look at the the items you have purchased to try and figure it out.

Cheers!

**Comment by gthapar** [comment]
I just tried to echo out plugin names and I got this result -
```
-
WPBakery Visual Composer
-
Fbar Plugin
-
Quform
-
<br>
<b>Notice</b>:  Undefined index: previews in <b>/Users/GT/Work/btnsx/wp-content/plugins/envato-market/inc/api.php</b> on line <b>341</b><br>
Usernoise Pro
-
Slider Pro
-
```

Seems like Quform is the culprit. :)

**Comment by valendesigns** [comment]
I'll have to check what the API response is for that item, though in any case a check for the image needs to be added which I'll do in the next few days.
