### ISSUE TITLE
Settings page is not loaded

### ISSUE THREAD

**Issue by kalonya** [envato/wp-envato-market#170]
Wordpress 4.9.6, no plugin conflict, PHP 7.1, Memory limit is 512M

<img width="1440" alt="screen shot 2018-05-26 at 12 22 41" src="https://user-images.githubusercontent.com/16854238/40574719-aee9dba2-60df-11e8-812b-b7b52e4ce5a5.png">

The error message:
TypeError: jQuery('#mwb_tyo_selected_address').select2 is not a function. (In 'jQuery('#mwb_tyo_selected_address').select2({
		placeholder: mwb_tyo_new_param.selec_address_placeholder,
		})', 'jQuery('#mwb_tyo_selected_address').select2' is undefined)

**Comment by manouallou** [comment]
+1 on this. I am getting a blank settings page too as kalonya mentioned.

**Comment by dtbaker** [comment]
Hi @kalonya thanks for that detailed error message.

The JavaScript error in that console is to do with `mwb-tyo-new-tracking.js` which is not part of the Envato Market plugin.

This sounds like a tracking script, which may not be desirable to have on your website, especially in the WordPress back end. Please disable all themes and plugins (or at least provide a screenshot showing all activated themes and plugins so we can see which one might be causing this error).
