### ISSUE TITLE
Bug with installed but not active plugins

### ISSUE THREAD

**Issue by vergedesign** [envato/wp-envato-market#18]
Sorry, i have never used github before so forgive me if im leaving out some sort of protocol. Im not a developer, but i made this account just for contributing to this plugin.

There is an issue, where when a plugin is already installed but not activated, the button tells you to install regardless. When you hit the install button,there is an error of the directory already being present.

Thats all. Peace

**Comment by valendesigns** [comment]
Could you please give more details? Screen shots are always very helpful in this situation.

Cheers!

**Comment by valendesigns** [comment]
Without a response I'm going to close the issue. It's more than likely you have installed the plugin in the wrong directory and it's unable to verify that the plugin was installed because of it.
