### ISSUE TITLE
Updating.... stuck

### ISSUE THREAD

**Issue by Uranbold** [envato/wp-envato-market#19]
Hello,

I have Multisite installed on my local mashine if i update themes then it's keep updating and stuck.

Environment: 
     Wordpress version 4.4
     API has full access token.

Anyone have similar issue or is this not working on local?

**Comment by Uranbold** [comment]
FYI,

https://drive.google.com/file/d/0Bz6KH9-v_ZLGZDRvaUVYOC13OUU/view

**Comment by valendesigns** [comment]
The updates can take several minutes to complete as the files are sometimes 100's of MB's. Also, without looking at the console output and showing me what the error message is I can't really do much to help you. Could you gather more information to help troubleshoot? Thanks.

**Comment by manake** [comment]
My updating is also not working.

1. I go to /wp-admin/admin.php?page=envato-market
2. I click "Update Available".
3. I always get "Update Failed: Plugin update failed."

All other updating from WordPress repository works.

Yesterday I was getting "Failed to load resource: the server responded with a status of 503 (Service Unavailable)" but today I don't see any errors in the console.

**Comment by valendesigns** [comment]
Is it possible you exceeded your limit of 20 daily downloads per file somehow?

**Comment by valendesigns** [comment]
And is the issue persisting?

**Comment by valendesigns** [comment]
Closing for lack of response, re-open if the issue is still persisting.
