### ISSUE TITLE
Disregard case when comparing item name and author name

### ISSUE THREAD

**Issue by Stephen-Cronin** [envato/wp-envato-market#20]
From time to time authors change their author name or the item name in style.css for a theme (the main plugin file for a plugin). When this happens, the plugin can no longer detect updates for that item.

While perhaps nothing can be done about this for most changes, the plugin should probably be able to deal with instances where only the case changes, eg: the name changes from 'My Theme' to 'My theme'. This does actually happen! I just had a case of this with the Toolkit plugin.

Would it be possible to use strtolower on both side of the compare so that it will still match items where only the case has changed? Thanks.

**Comment by dtbaker** [comment]
This is where an `envato.json` kinda file in every Theme/Plugin root would allow for name changes and other fancy things without breaking updates. e.g. https://github.com/dtbaker/envato-theme-and-plugin-updates

**Comment by Stephen-Cronin** [comment]
Yeah, I actually think that's a very good idea. If we had some way (such as the suggested json file) to match the item on it's unique id which never changes, rather than on the title and author name which do change, the plugin would be more robust. 

I had another case today where the Toolkit plugin isn't detecting the update because it's not matching on author name.

I might point some people to look at this issue and see if I can get a discussion going.

**Comment by dtbaker** [comment]
I've also seen buyers upload themes via ftp and choose their own theme
folder names. I haven't tested this myself but I'm pretty sure that would
break auto updates.

**Comment by valendesigns** [comment]
At this point the only thing we can legitimately do from the plugin is attempt to normalize those fields in some way, like lowercase during the check. As well, we could prepare for the future by supporting an `envato.json` file or similar standard before it's adopted by the Market as a whole. As for directory name changes I haven't tried that, though I suspect it will fail to update. We'll need to test that out and verify it.

**Comment by dtbaker** [comment]
What is the best way to read a `theme.json` file (if one exists) from the theme root folder?

```php
  $theme_json_file = trailingslashit( $theme->get_template_directory() ) . 'theme.json';
  if( is_readable ( $theme_json_file ) ) {
    require_once( ABSPATH . 'wp-admin/includes/file.php' );
    WP_Filesystem();
    global $wp_filesystem;
    $theme_json = json_decode( $wp_filesystem->get_contents( $theme_json_file ), true );
  }
```

I can do a quick pull request to modify the `process_themes()` method to check for a `theme.json` file and a match between any `envato-id` and a purchased theme id. 


Here's a sample of the `theme.json` file I'm using in Grunt for packaging up themes and hooking into the TGM plugin activation class. This ends up in my theme zip file so could be checked against Envato Market. 



```
{
  "slug": "beautiful-watercolor",
  "name": "Beautiful Watercolor",
  "wordpress_namespace": "beautiful",
  "version": "1.6.5",
  "live": {
    "url": "http://beautiful.dtbaker.net/"
  },
  "grunt": {},
  "envato-item-id": 14157442,
  "url": "http://themeforest.net/item/beautiful-watercolor-hand-painted-creative-wordpress/14157442",
  "author": {
    "name": "dtbaker",
    "url": "http://dtbaker.net"
  },
  "plugins": {
    "contact-us-widget": {
      "name": "Contact Us Widget",
      "local": true,
      "required": false
    },
    "dtbaker_banner": {
      "name": "dtbaker Banner",
      "local": true,
      "required": false
    },
    "dtbaker_visual_columns": {
      "name": "dtbaker Visual Columns",
      "local": true,
      "required": false,
      "config": {
        "column_styles": {
          "border2": "Line Border",
          "border1": "Nice Border",
          "box_style1": "Box Style 1",
          "box_style2": "Box Style 2",
          "box_style_flowertopbot": "Flower Top/Bottom",
          "box_style_background": "Nice Background"
        }
      }
    },
    "widget_anywhere": {
      "name": "Widget Anywhere",
      "local": true,
      "required": false
    },
    "widget_area_manager": {
      "name": "Widget Area Manager",
      "local": true,
      "required": true
    },
    "envato-market": {
      "required": true,
      "name": "Envato Market",
      "source": "https://envato.github.io/wp-envato-market/dist/envato-market.zip"
    },
    "woocommerce": {
      "required": false,
      "name": "WooCommerce",
      "wordpress": true
    }
  }
}
```

Something to consider with an Envato theme json file. When initially submitting the item to Envato the author will not know the item id. So this file could be generated automatically when theme is approved?
