### ISSUE TITLE
Bug : WP Envato Updater Installed But Not Active. But Showing Activate the Envato Market plugin 

### ISSUE THREAD

**Issue by technofreaky** [envato/wp-envato-market#21]
I have created a plugin and included https://github.com/envato/wp-envato-market/blob/master/inc/github.php in my plugin.. 

and in my localhost. WP Envato market plugin is not activated. but in my admin its showing to active the envato products. it actually should show to active the envato updater plugin

Image : http://prntscr.com/9lta54

**Comment by valendesigns** [comment]
I'm not following here. Is the plugin activated or deactivated?

**Comment by technofreaky** [comment]
@valendesigns 

Envato Updated is deactivated and the other plugin which has the integration is active. but a admin notice showing to register the paid pluign with the Envato Updated

**Comment by valendesigns** [comment]
That notice is telling you to activate the Envato Market plugin.

**Comment by valendesigns** [comment]
The behavior is working as expected. When you include the `github.php` file in your item it creates a notice to install the plugin, when the plugin is installed there is then a notice to activate the plugin. Everything is working as expected from what I can tell and there isn't a bug.
