### ISSUE TITLE
Add GIT support

### ISSUE THREAD

**Issue by manake** [envato/wp-envato-market#23]
Can Envato Market also have GIT support?

That is: authors should be able to push changes immediately to Envato server without review. "Envato Market" plugin should have an option to allow downloading:
<ul>
<li>"stable version reviewed by Envato team"</li>
<li>"development version not reviewed by anyone" (with a proper warning that Envato nor author take responsibility for how development versions work)</li>
</ul>

This is much needed because:
<ol>
<li>It takes a lot of time to resubmit theme/plugin updates to TF/CC. Authors update items less often then.</li>
<li>Critical updates are not immediately available but with up to a couple of days delay.</li>
<li>When someone finds a bug and asks for support then author has to resubmit the whole plugin/theme to fix that (client has to wait 1-7 days for an update) and they could immediately add a fix for the person that has found it.</li>
</ol>

Generally, there are only benefits. Please don't ignore this request like you always do (like when Envato community waited 2-5 years for better ratings, statistics, ability to customize invoice details etc.). TF/CC involve code so they should have tools like github.com for working with code. Issue tracker and proper version control.

**Comment by valendesigns** [comment]
Unfortunately, your request is out of the scope of this plugin right now. There aren't currently plans to add `git` support and you would need to take it up with someone at Envato who can make policy changes. I'm only the developer. Sorry!
