### ISSUE TITLE
Fatal error on frontpage

### ISSUE THREAD

**Issue by matijamrkaic** [envato/wp-envato-market#24]
If plugin installer (github.php) is included but not installed, on frontpage it will throw:

    Fatal error: Call to undefined function get_plugins() in 
    .../wp-content/themes/.../github.php on line 222

Currently, I've worked around the issue by checking if `is_admin()`.

**Comment by dtbaker** [comment]
Another user reported this on the forums too: https://forums.envato.com/t/envato-market-wordpress-plugin-beta/21639/38?u=dtbaker

**Comment by valendesigns** [comment]
I'll have time this weekend to troubleshoot the issue.

**Comment by dtbaker** [comment]
From: https://codex.wordpress.org/Function_Reference/get_plugins

```
// Check if get_plugins() function exists. This is required on the front end of the
// site, since it is in a file that is normally only loaded in the admin.
if ( ! function_exists( 'get_plugins' ) ) {
	require_once ABSPATH . 'wp-admin/includes/plugin.php';
}
```

**Comment by valendesigns** [comment]
The plugin doesn't need to load on the front-end so it's probably best to not load when in that context.

**Comment by jashjacob** [comment]
Just noticed this issue pop up after an update. 👎
