### ISSUE TITLE
Tag a 1.0.0-RC version

### ISSUE THREAD

**Issue by capuderg** [envato/wp-envato-market#25]
Hi,

could you please create a tag, so we can use it in TGMPA (so that we do not include the changing master or 1.0.0-RC branch)... 

Thanks!

PS: nice work with this plugin. This current version in master works great!

**Comment by valendesigns** [comment]
The master is only ever the most recent release.

**Comment by capuderg** [comment]
yes exactly, that's why it would be nice to have a tagged, working and stable version (without the most recent changes).

**Comment by valendesigns** [comment]
The plugin is still under development, so technically it's not stable until I tag v1.0.0 though the master is essentially a tag of the next stable pre-version as there are not going to be commits to it other than for RC versions up until the stable v1.0.0. I'm not sure I see why tagging a pre-release is helpful here. All commits to master are for major, minor, and hotfix merges now and in the future. Each revision to master will be adding stability to the plugin and not introducing regressions or blockers. I follow a strict branching strategy and the master is always the stable branch so the next merge will be the 1.0.0-RC1 branch into master after going into wip first. There will likely be only 2 RC's and the second one being mainly text/copy changes and polishing any rough edges, RC1 will fix bugs which I would assume you would want to have, not avoid. You will be safe using master without any tags.

**Comment by capuderg** [comment]
Aha, ok I understand. I thought that master is the main dev branch...

Thanks!

**Comment by valendesigns** [comment]
No worries, the `wip` is the main dev branch. The only branches created from and merged directly into `master` are hotfixes. Also, the ZIP archive in the `gh-pages` branch is technically the best source to use for a stable installable WP package for end users. It's how the plugin updates itself.
