### ISSUE TITLE
Update notice is not displaying in multi-site

### ISSUE THREAD

**Issue by wpexplorer** [envato/wp-envato-market#27]
When there is an update available it needs to display a notice that is visible on the entire admin (simple modification) not just in the Envato Market admin page because people don't want to open up the Envato admin page every time they log into their WP dashboard.

Same with the Envato Toolkit  - https://github.com/envato/envato-wordpress-toolkit

Thanks!

**Comment by valendesigns** [comment]
If you're talking about when the plugin itself has an update then the notice should be displayed everywhere in the Admin except the `update-core` & `update` screens, and when a plugin is being deleted on the `plugins` screen. Are you having a different experience than that? If you're talking about themes and plugins, it notifies the user in the same way Core does through the themes or plugin screens and on the Envato Market screen. Not sure how it could be better than that?

**Comment by wpexplorer** [comment]
When testing it's not displaying the notice in the plugins or themes screen (using multi-site and testing on single and network admin screens). It only displays the notice on the Envato Toolkit page (sorry I haven't looked in the actual code to see how things are setup to provide better feedback). I tested deleting the update_themes transient to make sure as well.

Thanks!

**Comment by valendesigns** [comment]
The __Envato Market__ plugin shows updates on `update-core.php`, `plugins.php`, and `themes.php` in addition to `admin.php?page=envato-market`. Not sure why you are having issues other than maybe it's a multi-site specific issue. I'll have to test it in my VIP-Quickstart environment to verify.

**Comment by valendesigns** [comment]
The update notices correctly display in Multisite, you can see them for both themes and plugins on the Network Admin pages. I tested this using vvv-multisite. Also, if you are logged in as a super admin you will be able to upgrade themes & plugins from the Envato Market plugin with Ajax inside a site, which is an enhancement to the previous UX not a bug.
