### ISSUE TITLE
Admin bar not visible in front end when using BbPress + BuddyPress

### ISSUE THREAD

**Issue by cubell** [envato/wp-envato-market#28]
Hey Derek,

Great plugin, however, I integrated the plugin to one of my themes recently, and for the most part it seems most users don't have issues. But apart from the "get_plugins()" issue already reported, I have recently also received a handful of reports from users saying their admin bar stopped appearing, but everything else seemed to work well.

There were no Javascript or PHP errors, but simply deleting the github.php loading line fixed it.

I then figured out the combo that does it. And you can recreate it with TwentySixteen, simply install and activate BuddyPress + bbPress, and then add `require_once get_template_directory().'/github.php';` to the functions.php + put the github.php file in the root of the theme folder. And the admin bar will not appear on the front end.

Activating the Envato Market plugin then makes the admin bar re-appear.

Thanks for all the hard work, Derek!

Cubell

**Comment by valendesigns** [comment]
This should be fixed by https://github.com/envato/wp-envato-market/commit/da0802354ffb169e78b9cd7d0066731ae3b13042 which will be released soon. Could you please test the RC1 branch to verify?
