### ISSUE TITLE
Is this still a beta version?

### ISSUE THREAD

**Issue by jouriena** [envato/wp-envato-market#34]
Hi, 

I'm wondering if Envato Market wordpress plugin is still a beta version. 

I've been using the plugin for about 2 weeks now and I've had 3 issues.

1) It seems that the synchronisation of the plugin and my envato account is not real-time...well, it was hinted by the word "periodically", but I'm just wondering how periodical is it anyway? I've purchased a  plugin on CodeCanyon 3 days ago, and it still doesn't appear on Envato Market plugin.

Or is this the problem with the plugin's author side? 

2) Single Use OAuth Personal Tokens is not working. It keeps saying that either the token or the Item ID is invalid. It worked with the first set of plugins the first time I used the Envato Market plugin though. 

3) One of the plugins I've purchased has been installed and activated through Plugins > Add New > Upload, but the Envato Market plugin doesn't seem to recognize that, as the button is still labeled as "Install" instead of "Deactivate". I tried removing the plugin in question and reinstall it using Envato Market plugin, but the button is still labeled as "Install" regardless.

I'd appreciate any advice on this. 

Regards, 

John

**Comment by valendesigns** [comment]
Did you create your token here?

https://build.envato.com/create-token/?purchase:download=t&purchase:verify=t&purchase:list=t

**Comment by jouriena** [comment]
I also tried using the token created in this link too, yes. It didn't work.

*Klas & Sylph*
Lenuine Marketing Co., Ltd.

M: 086 902 0880
F: 02 336 1346
E: info@klassylph.com
W: www.klas-sylph.com
Instagram: KlasSylph
Facebook: Klas & Sylph (Thailand)

**Comment by weechoochter** [comment]
I love the idea of this plugin but I also get the same error when trying to use OAuth Personal Tokens: the token or the Item ID is invalid. A tutorial or some documentation would be great. The documentation available seems to be for developers and how they can use the API to make calls for their own plugins.
So I am not using it all.
Thanks

**Comment by valendesigns** [comment]
There should only be two reasons a token is invalid, a third for single use tokens. First, the permissions were not correctly set and the token is unable to access certain parts of the API, like downloading or has been revoked. Second, the 24 hour download limit has been reached for an item or some other API related outage. Third, the item does not have an installable WordPress package.

I hope that helps you guys, but I can't think of any other "normal" reasons that message would be returned.
