### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by vincxxc** [envato/wp-envato-market#35]
Hi,

installed the plug, create the personnal token and entered it then I have this error : 
"The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions."

What am I suppose to do?

**Comment by valendesigns** [comment]
What permissions did you create the token with?

**Comment by valendesigns** [comment]
You can generate a valid token by going to this URL.

https://build.envato.com/create-token/?purchase:download=t&purchase:verify=t&purchase:list=t

**Comment by vincxxc** [comment]
Hi, that's the page where i've already set a token.
The permissions checked was : view an search envato sites, download your purchased items, verify purchases you've made, list purchases you've made.

**Comment by ReactorFan** [comment]
Hi there, I'm bumping into the same error. The error message keeps popping up, also after creating a new token and giving it full access... Vincxxc, did you manage to find a solution? Or did you manually update the theme? That's a drag... mostly because I'm not a programmer. Would be nice to get an update, thanks!

**Comment by valendesigns** [comment]
Please add the token globally and see if it works that way for troubleshooting purposes.

**Comment by valendesigns** [comment]
Reopen if you are still having issues.

**Comment by paulabishop** [comment]
I am also having this issue and it's driving me crazy! I have generated a token three times, and each time I try to "Test API connection" it gives me the same error message "The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions." I have followed the link above in this thread, and I have also tried a key with many more permissions than required. How to fix this?!
