### ISSUE TITLE
how to add Single Use OAuth Personal Tokens

### ISSUE THREAD

**Issue by BENYSALIM** [envato/wp-envato-market#36]
how to add Single Use OAuth Personal Tokens ?
i can not find document how to add Single Use OAuth Personal Tokens

**Comment by valendesigns** [comment]
You create an Envato API token by clicking the link on the plugin admin page in WordPress and enter that token and the ID of the item into the single use field and click save.

**Comment by BENYSALIM** [comment]
CAN NOT WORK

**Comment by BENYSALIM** [comment]
The Token or Item ID is incorrect.

**Comment by BENYSALIM** [comment]
Global OAuth Personal Token IS WORK, BUT Single Use OAuth Personal Tokens NOT WORK.
i fill token same with Global OAuth Personal Token and Item ID like 1904470.it is not work for single use oauth personal tokens
