### ISSUE TITLE
Single Use OAuth Personal Tokens Add Item fails

### ISSUE THREAD

**Issue by galbaras** [envato/wp-envato-market#37]
When trying to add a single item through the plugin, I get "The item cannot be downloaded", although the token is being used on 2 other sites successfully and the item number is correct.

There are no hints in error_log files anywhere. Latest version installed.

Steps: click Add Item, enter token and item ID, hit Save.

**Comment by valendesigns** [comment]
Is it possible you hit the download limit of 20 for a 24 hour period through all of your sites?

**Comment by galbaras** [comment]
No. It only seems to be this one item.

**Comment by valendesigns** [comment]
I can take a look, but you will need to send me the token and item ID to derek@valendesigns.com

**Comment by valendesigns** [comment]
I believe the issue is that the item does not have a downloadable package. Contact the item author and ask them to upload a WordPress downloadable package.

**Comment by galbaras** [comment]
Hey Derek,

Generating a new token made it work, so it wasn't the download package. Maybe it was the number of sites using the same token (this one was the third)?

Cheers,
Gal
