### ISSUE TITLE
Plugin not updating the theme

### ISSUE THREAD

**Issue by WakeUpCallProject** [envato/wp-envato-market#42]
Hi,
I have a new theme update for 'Sahifa' wordpress theme.
In the past there was a button/link I clicked that updated my theme but now there is just a 'customise' button.
How can I update the theme with the Envato plugin?
Thanks

**Comment by WakeUpCallProject** [comment]
My token is active too: 
"Your OAuth Personal Token has been verified."

But still no option to update the theme with the plugin.

I see there is a "Activate the Envato Market plugin to get updates for your ThemeForest and CodeCanyon items."

When I click into that I get the message:
"Plugin file does not exist."

Can you please help me?

**Comment by valendesigns** [comment]
Have you installed the plugin using this package? http://envato.github.io/wp-envato-market/dist/envato-market.zip

**Comment by sandro231156** [comment]
Hi, i've installed envato market, and get follosing mssg: Your OAuth Personal Token has been verified. However, there are no WordPress downloadable items in your account.
please advise
thanks
sandro

**Comment by valendesigns** [comment]
If the plugin says there are no packages you can download then jupiter is not setup correctly on the API side, please contact the plugin author and tell them to upload an installable WP package to fix the issue or contact Envato support.
