### ISSUE TITLE
conflict with WP Layerslider

### ISSUE THREAD

**Issue by timeassistant** [envato/wp-envato-market#45]
I have noticed that Envato Market plugin and the Layerslider Plugin conflict. 

When both are active the Themes and Settings tabs do not display any content just the Tab title itself. I'm not certain but I think its possibly a js error.

Layerslider is premium plugin and is available from these 2 locations:

https://kreaturamedia.com/layerslider-wordpress-full-width-slider/
http://codecanyon.net/item/layerslider-responsive-wordpress-slider-plugin-/1362246

I dont think it makes a difference but Layerslider is pre-bundled into a theme we use which is here:

http://themeforest.net/item/bridge-creative-multipurpose-wordpress-theme/7315054

**Comment by valendesigns** [comment]
Can you look at the dev tools in Chrome and see if there is a JS error?

**Comment by timeassistant** [comment]
Hi sorry for the delay ! Had a very busy period in work.

Yes there are a few errors that I can see, I use firefox so the output may be slightly different. (I attached a screenshot below)

![screenshot 066](https://cloud.githubusercontent.com/assets/18701905/15866583/2eabb34a-2cd7-11e6-9580-773d97e85755.PNG)

if you need extra / different info please let me know !

**Comment by valendesigns** [comment]
It looks like there is a JS error in the default.js file which is causing this plugin to fail.

**Comment by timeassistant** [comment]
So that would be the default.js located inside the bridge theme /wp-content/themes/bridge/js/admin/default.js 

Is this something you could fix your side or perhaps contact Qode (makers of bridge) to try and resolve between you both? The bridge theme is very extensive and has lots of features and functionality so this may need some work
