### ISSUE TITLE
Activate the Envato Market plugin

### ISSUE THREAD

**Issue by Ataurr** [envato/wp-envato-market#46]
I have just download this to update one of my item from themeforest. but i am getting a issue.
in top i am getting message. "Activate the Envato Market plugin"

http://puu.sh/oyxqC/1374b530b6.png

but when i click this i saw a message. http://puu.sh/oyxsq/faa271f0ba.png
but plugin file still exist. and i have update my theme with this.

**Comment by valendesigns** [comment]
Did you install the plugin into the `/plugins/envato-market` directory?

**Comment by Ataurr** [comment]
Yes i am download half hour ago. http://puu.sh/oyxGd/424dd15ec0.png

**Comment by valendesigns** [comment]
You need to download it from here http://envato.github.io/wp-envato-market/dist/envato-market.zip not directly from the Github download button. This information in is the readme. Please reinstall the plugin or change the directory name from `wp-envato-market` to `envato-market`.

**Comment by Ataurr** [comment]
Thanks. Its work now.
BTW i think you should add a io page link on top here. http://prntscr.com/axs0q1

Or first position in Readme file. "Download Stable version" like this

Thanks very much for help

**Comment by valendesigns** [comment]
Added the link and thanks for the input. Cheers!
