### ISSUE TITLE
Unable to update 'Woocommerce Color or Image Variation Swatches'

### ISSUE THREAD

**Issue by katmoody** [envato/wp-envato-market#49]
Not sure if it's just a glitch but have tried to update this one several times to no avail. 
<img width="500" alt="screen shot 2016-06-05 at 11 21 11 am" src="https://cloud.githubusercontent.com/assets/5481211/15806360/a7aa1f80-2b0f-11e6-80bc-c3c08e047574.png">

I'll be going ahead and updating this one manually unless there is information you can use that I can get for you beforehand?

**Comment by valendesigns** [comment]
Try deleting the plugin you are having trouble with and then installing it using this plugin. It could be that if you manually installed it the server permissions are not letting you write over the directory and plugin files.
