### ISSUE TITLE
can not be activated side wide (MU Site)

### ISSUE THREAD

**Issue by Tobias-Conrad** [envato/wp-envato-market#50]
side wide activation it does not show in the menu on the left.

**Comment by Tobias-Conrad** [comment]
when i enable only per site it is viewing

**Comment by barartm** [comment]
same issue here, the old "envato-wordpress-toolkit" enabled it on the main dashboard and not per site, this is annoying if i have a lot of sites i need to login one by one and put api on all of them also check themes one by one, in that case is easy check all themes in my download page and match them in my installed themes so this plugin brokes the funcion of check and update themes and ceases to use it.. this plugin must work as the older "envato-wordpress-toolkit" only for main dashboard on multisite and not per site.

Also i would like to have a option to add more than one user/api sometimes my clients buy their themes with their account and i would like to have the option to add them to the plugin to keep all themes updated.

**Comment by barartm** [comment]
Nobody else comment on this... im still using the old "envato-wordpress-toolkit"

**Comment by barartm** [comment]
........

**Comment by Merl** [comment]
@barartm you´ve said it all. would be nice to have a real multisite ready version as well as the ability to enable more api keys for different envato accounts.

**Comment by dtbaker** [comment]
We are releasing version 2.0.1 of the market plugin shortly. This should solve some issues or at least give a more detailed error message.
