### ISSUE TITLE
Envato Market Plugin Not Working

### ISSUE THREAD

**Issue by Evelyn7** [envato/wp-envato-market#52]
Hello+

I approached Envato Market Help regarding the following issue:

I have downloaded the envato-market.zip from here: http://envato.github.io/wp-envato-market/
I have followed the Installation instructions found on that same page.
When I click the "Envato Market" menu in WP, I get the following error message:
Fatal error: Call to undefined function wp_scripts() in /home/content/87/13013687/html/wp-content/plugins/envato-market/inc/admin/admin.php on line 378
Please advise...

Envato Replied:

We'll need to get the developer who maintains the Envato Market plugin to look into the issue. The easiest way to do this is to create a new issue over on the GitHub repo:
https://github.com/envato/wp-envato-market/issues/new

So, now I am reaching out to you... Please let me know what additional information you need to advise/assist me on this problem.

Thank you,
+ES

**Comment by valendesigns** [comment]
What version of WordPress are you using?

**Comment by valendesigns** [comment]
Also what version of PHP?

**Comment by Evelyn7** [comment]
Hi+
I'm using WP 4.1.2 & PHP 5.3.24
I plan to update once I get things installed & activated (& backed up), but it won't install/activate - so I'm  sort-of stuck...
Thank you very much!

**Comment by valendesigns** [comment]
Your version of PHP is fine but the plugin is not tested in 4.1 so that's likely the issue.

**Comment by Evelyn7** [comment]
Okay, what do I need to do? 
I really would like to use the Envato Plugin to update this site's theme... Please advise...
Thank you!

**Comment by valendesigns** [comment]
You need to upgrade WordPress first.

**Comment by woodcamp** [comment]
Am hosting with wpEngine.com. WordPress Version: 4.5.2 - if the Envato updater is not playing nice with the current version of WP, when will it? Will your updater self update to the version that does play nice with the latest version?? How should updates be obtained in the meantime?

**Comment by sloantech** [comment]
I am also on wpEngine WP version 4.5.2 and php 5.5.9. Envato's updater does not seem to be updating my Theme either. I really need a way to keep all my Envato themes and plugins updated automatically, as manually doing it varies slightly from theme to them and generally takes too much time. (fingers crossed.)

**Comment by GideonLupine** [comment]
I am running Wordpress 4.5.3.
PHP 5.5.35
Hostgator

I too get the error for "Activate the Envato Market plugin to get updates for your ThemeForest and CodeCanyon items."

If I click the word Activate, I get "Plugin file does not exist."

**Comment by sloantech** [comment]
Oh the frustration....I need an automated way to make sure all Envato plugins and Themes stay up to date and secure, but this WP Envato Market plugin does not seem to be working. Any ideas?

**Comment by Evelyn7** [comment]
Hello+
Just thought I would provide an update... I did update my WP to the most recent release and then installed the Envato Market Plugin. It activated and set up without issue and is working just fine on that site... Now I need to go to my other sites and update each of them to the newest WP release, then remove the old Envato Plugin and install this new Envato Plugin... 
Thank you @valendesigns for the guidance!

**Comment by slaving** [comment]
"Plugin file does not exist." - check that plugin install from zip with name wp-envato-market.zip and folder inside wp-envato-market too.

**Comment by ericbullet** [comment]
on first install there is a nag prompt that says: 
Activate the Envato Market plugin to get updates for your ThemeForest and CodeCanyon items.

when you click the link it an error is shown: 
Plugin file does not exist." - check that plugin install from zip with name envato-market.zip and folder inside envato-market too.

however the plugins activates.

**Comment by niczee** [comment]
Plugin is Activated.
Notice Says:
Activate the Envato Market plugin to get updates for your ThemeForest and CodeCanyon items.

![image](https://cloud.githubusercontent.com/assets/15862471/24569609/835e57be-162c-11e7-9e13-2adaacced524.png)

Clicking the link leads to:

![image](https://cloud.githubusercontent.com/assets/15862471/24569620/90346ed8-162c-11e7-8fd8-5b8c5c5bd4d1.png)

**Comment by gerardjp** [comment]
+1 on the: Plugin doesn't exist.

wp: 4.7.3
php: 5.5.9
