### ISSUE TITLE
define minimum permissions needed

### ISSUE THREAD

**Issue by ewsopp** [envato/wp-envato-market#53]
When creating an envato api key, there are plenty of permissions. What are the minimum required for this plugin to function? maybe define these in a wiki page or in the readme.

![image](https://cloud.githubusercontent.com/assets/5578537/16312476/ed2e00da-3942-11e6-895e-5c8f8b5e7c57.png)

**Comment by valendesigns** [comment]
When you click the link in the admin page it autofills the required permissions.

**Comment by ewsopp** [comment]
Ok thanks

Here is a screenshot of those required permissions for anyone curious...

![image](https://cloud.githubusercontent.com/assets/5578537/16635584/12f27fe0-43a1-11e6-9d17-2a6266d0e40e.png)
