### ISSUE TITLE
Plugin Not Displaying Settings

### ISSUE THREAD

**Issue by bradoliver** [envato/wp-envato-market#56]
We've tried several times, following the directions perfectly but we can't get this plugin (1.0.0-RC2) to work.  Each time the "Settings" tab is completely blank.  Screenshot attached.

Chrome or Safari (latest versions) same results.

Any thoughts?

![envato_market_ _sweetcode_io_ _wordpress](https://cloud.githubusercontent.com/assets/12043921/17190064/42d6c82a-53f9-11e6-84f7-04c148324ef4.png)

**Comment by debstar73** [comment]
Hi
I had the same thing. But if you just click on the Settings label, the options will appear.

**Comment by bradoliver** [comment]
Thanks.  Forgot to mention that I had tried and that it doesn't work either.  Even tried "Open in New Tab" and still nothing.

**Comment by valendesigns** [comment]
What version of WordPress are you running?

**Comment by bradoliver** [comment]
4.5.3

**Comment by bradoliver** [comment]
Let me try a different host/site...  back in a few.

**Comment by bradoliver** [comment]
Different host/server
Different domain
WP v4.3.5  (not a typo)
Theme: 1Page (same as above)

**Comment by valendesigns** [comment]
Could you look and see if there are any JS errors in Chrome dev tools?

**Comment by bradoliver** [comment]
Hopefully this is what you want...

![envato_market_ _wordpress](https://cloud.githubusercontent.com/assets/12043921/17265917/e8651620-55a7-11e6-9178-56c2ab721bdb.png)

**Comment by bradoliver** [comment]
Ack!  Did a little searching and figured it out, it's a plugin conflict.   Client was using WPMU's Custom Sidebars Pro plugin.  As soon as I deactivated it, the settings screen appeared.

So that then begs the question... Which plugin is the root of the conflict?  :-)

**Comment by bradoliver** [comment]
I've done a little more testing and can confirm what I said above.  If I reactivate the WPMU Custom Sidebars plugin, the error comes back.  BTW, the error provides no more info when expanded.

**Comment by valendesigns** [comment]
Seems like their JS is leaking into other admin pages. Is it a free plugin that I can download somewhere?

**Comment by bradoliver** [comment]
https://wordpress.org/plugins/custom-sidebars/

At first I thought they were running the pro (paid) version, but it is the free version they have installed.

**Comment by valendesigns** [comment]
I'll see if there is a quick fix we can make for the next release that dequeues the script on the EM plugin page or fixes the conflict some other way. I'm busy with a project this weekend but will look into it ASAP.

**Comment by dtbaker** [comment]
Seems ok with latest version of this WPMU plugin installed.
