### ISSUE TITLE
Page is missing completely any plugins / themes

### ISSUE THREAD

**Issue by uhlhosting** [envato/wp-envato-market#61]
Hello,

The plugin has the proper API key yet is not displaying any items.

**Comment by highacid** [comment]
The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions.
Yet I am sure it was working fine. And now suddenly it isn't anymore.

**Comment by dtbaker** [comment]
There have been some recent API changes. Hey please let us know if this is still an issue and we can look into it further.
