### ISSUE TITLE
Stuck on "Refresh" while them update

### ISSUE THREAD

**Issue by kleinechristoph** [envato/wp-envato-market#62]
I am trying to update my wordpress theme re:hub via the envato plugin. But it gets stuck on the refresh status, rather than finishing the update. Last time it worked fine. (screenshot attached)

![envato-wp-plugin-stuck](https://cloud.githubusercontent.com/assets/12375918/17922671/7f31c8e0-69e0-11e6-82d8-a4d5f852d447.GIF)

I am using version 1.0.0-RC2 of the envato market plugin and the latest wordpress version.

**Comment by 4loveofpunk** [comment]
Same issue here. See there is a theme update, hit update, spins endlessly but no update. Several sites on a dedicated CentOS 6 server so I'm pretty sure it's not a hosting issue. Envato Toolkit used to update, but this doesn't.

Any more details anyone might need I can certainly get them.

**Comment by kleinechristoph** [comment]
I actually managed to update the theme from a different view in the backend. Which is OK, but the issue still appears to be weird,

**Comment by robotiko** [comment]
Same issue here. 
Tried from several views and always fails.

**Comment by olenlomalla** [comment]
I have same issue. Any suggestions?

**Comment by fajekaidee** [comment]
same issue here…

**Comment by dtbaker** [comment]
There have been some recent API changes. Hey please let us know if this is still an issue and we can look into it further.
