### ISSUE TITLE
Warning: Invalid argument supplied for foreach....

### ISSUE THREAD

**Issue by fritjg** [envato/wp-envato-market#63]
Hello,

I have on all my pages all the same problem. you have a solution?

Thanks for Help...

Warning: Invalid argument supplied for foreach() in XXXXXXXXXX/wordpress/wp-content/plugins/envato-market/inc/api.php on line 320

Warning: Invalid argument supplied for foreach() in XXXXXXXXXX/wordpress/wp-content/plugins/envato-market/inc/api.php on line 320

Warning: Invalid argument supplied for foreach() in XXXXXXXXXX/wordpress/wp-content/plugins/envato-market/inc/api.php on line 320

Warning: Invalid argument supplied for foreach() in XXXXXXXXXX/wordpress/wp-content/plugins/envato-market/inc/api.php on line 320

Warning: Cannot modify header information - headers already sent by (output started at XXXXXXXXXX/wordpress/wp-content/plugins/envato-market/inc/api.php:320) in XXXXXXXXXX/wordpress/wp-includes/pluggable.php on line 1174

Warning: Cannot modify header information - headers already sent by (output started at XXXXXXXXXX/wordpress/wp-content/plugins/envato-market/inc/api.php:320) in XXXXXXXXXX/wordpress/wp-includes/pluggable.php on line 1174

**Comment by fritjg** [comment]
Hello!

HeLp...please....

**Comment by galbaras** [comment]
+1

**Comment by galbaras** [comment]
The following code change can fix this:

```
	if ( isset( $v['value'] ) ) { // << Added
		foreach ( $v['value'] as $version ) {
			$versions[] = str_replace( 'WordPress ', '', trim( $version ) );
		}
	}  // << Added
```

**Comment by dtbaker** [comment]
Fixed. Thanks.
