### ISSUE TITLE
Add to WordPress plugin directory

### ISSUE THREAD

**Issue by michaelalhilly** [envato/wp-envato-market#65]
Why have us jump through hoops?

Just upload this wonderful plugin to the WordPress plugin directory so we can install it from within WordPress :)

**Comment by valendesigns** [comment]
It's not allowed to be in the WordPress plugins directory, I've tried on multiple occasions.

**Comment by michaelalhilly** [comment]
I was hoping you weren't going to say that.

Maybe because it's dependent on a paid product. However, this is a an exception. You're not trying to sell anything. It's just a helper plugin for the largest theme and plugin marketplace.

I'll write them. You never know.

Closing issue.
