### ISSUE TITLE
Envato market plugin not showing ADS PRO plugin

### ISSUE THREAD

**Issue by whatwewa** [envato/wp-envato-market#66]
Hello,
I bought three plugins from envato  market. Those are ConvertPlug, Easy social share buttons and ADS PRO.
I have installed envato market plugin and using Global Auth.
It is showing only two plugins. It is not showing AdsPro plugin.
What should I do?

**Comment by mohstar** [comment]
Hi there, I don't think it's related to / or because of envato market plugin, check your installation method, read it's documentation or contact the AdsPro plugin seller for support.

**Comment by dtbaker** [comment]
There have been some recent API changes. Hey please let us know if this is still an issue and we can look into it further.
