### ISSUE TITLE
No connection on all items since WP4.61

### ISSUE THREAD

**Issue by Angelito22** [envato/wp-envato-market#67]
Hey there,

I am having an issue that I suddenly cannot connect the envato market plugin anymore. Before it all worked great! All permissions are given and still no result. I always get the following message with all items:

"The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions."

Can anyone help please?

Thank you!

Matthias

**Comment by bachmay** [comment]
Same problem
