### ISSUE TITLE
How to update theme/plugins

### ISSUE THREAD

**Issue by isaumya** [envato/wp-envato-market#70]
Hi,
I used to use Envato Toolkit which had a easy to use update theme/plugin option. But with envato market I don't see any update theme/plugin button.

![2016-10-09_1-54-33](https://cloud.githubusercontent.com/assets/2124755/19215720/7a883ad4-8dc3-11e6-8b43-f2d5b6081cfa.jpg)

But I don't see an option to update the theme. In envato toolkit, there was an option called update.

Can anyone tell me how to perform update with this plugin? I really got no clue about it.

Also how to update the envato market plugin itself? Are you guys using WordPress [github updater script](https://github.com/afragen/github-updater) so that update can be pushed from Github to sites just like WP Repo update works? Or I have to manually check each day if there is a new version of this plugin available or not?

**Comment by dtbaker** [comment]
There have been some recent API changes. Hey please let us know if this is still an issue and we can look into it further.
