### ISSUE TITLE
Additional verification before updating an item.

### ISSUE THREAD

**Issue by capuderg** [envato/wp-envato-market#72]
Hi,

thanks for this plugin!

Would you maybe consider merging a PR for a WP action hook, which would allow theme/plugin authors to make some additional verifications, before the item is updated?

One case of additional verification would be, to check, if user has bought 1 licence for each install. The user would input the purchase code in the theme options and we would hook into this new WP action hook and interrupt the update with a message, if the user has used this purchase code on other sites as well...

Let me know and I can prepare the PR.

Take care!

**Comment by dtbaker** [comment]
@capuderg yes I plan to add a whole bunch of new hooks and documentation for authors to integrate more tightly into this plugin.
