### ISSUE TITLE
"Install" theme but no "Update" button

### ISSUE THREAD

**Issue by emotemarketing** [envato/wp-envato-market#73]
I know it's been asked but I haven't seen a solution yet. I have a client website using the theme from Envato - Oshine. I've installed the Envato Market plugin and it says "Install". It's already installed! What the what?

Anyone find a solution for this?

**Comment by JosKlever** [comment]
This might happen if the name of the theme folder has a different name than standard, like: Oshine-v2 instead of Oshine.

**Comment by dtbaker** [comment]
Yep unfortunately cannot fix this, majority of themes will work fine but if the author provided an incorrect zip file (or the theme was manually installed into a different folder name) then the automatic update process will not work.

The same is true for core themes and plugins. 

A solution here is to rename the theme folder via FTP, however ensure a full site backup is done first as you may loose some settings after re-activating the theme again.
