### ISSUE TITLE
'Updating' endlessly without completion

### ISSUE THREAD

**Issue by Spereicle** [envato/wp-envato-market#77]
Installed 1.0.0-RC2 from http://envato.github.io/wp-envato-market/dist/envato-market.zip

Created 'Single Use OAuth Personal Tokens' and successfully linked desired theme with following confirmations:
- All Single Use OAuth Personal Tokens have been verified.
- Theme shows as desired on 'Envato Market' plugin 'Themes' tab

After clicking 'Update Available', the status changes to 'Updating' and the throbber (spinning icon) begins to turn.

No further status changes happen, the throbber continues to spin, and the status text remains 'updating'.

My troubleshooting attempts:
Cleared local browser cache and restarted the process several times.
Let it run for more than 20 minutes each time.

![screenshot](https://cloud.githubusercontent.com/assets/12239124/21206827/3cf87d98-c219-11e6-9019-43c2b82245b5.png)

**Comment by KevinSleegers** [comment]
I'm experiencing the same issue, have you found a way to fix this?

**Comment by ideothemes** [comment]
The same issue...

**Comment by MohamedSahbi** [comment]
I have the same problem.

**Comment by GoktugOzturk** [comment]
I use single auth token and have the same problem.

Here is the xhr response when i click "update" button
{"success":false,"data":{"infinite":true}}

**Comment by phache** [comment]
I'm also experiencing the same issue.

**Comment by joaoreynolds** [comment]
Same issue, same theme! `{success: false, data: {infinite: true}}`

**Comment by dtbaker** [comment]
Is anyone else experiencing this issue any more? There have been some API changes that may have improved this. Please feel free to reopen this bug if it happens again.
