### ISSUE TITLE
WP-CLI install

### ISSUE THREAD

**Issue by szepeviktor** [envato/wp-envato-market#78]
Please consider mentioning WP-CLI install method

```
wp plugin install https://github.com/envato/wp-envato-market/archive/master.zip
```

Works with tagged zip-s.
Automatically strips off `-master` from folder name.

**Comment by dtbaker** [comment]
Thanks, will add to docs.

**Comment by szepeviktor** [comment]
@dtbaker Do you revive the plugin?

**Comment by dtbaker** [comment]
Yes. Plugin coming next week. Added wpcli docs to footer here: https://envato.com/market-plugin/

**Comment by szepeviktor** [comment]
Thanks.
