### ISSUE TITLE
updating theme through /wp-admin/admin-ajax.php gives error 500

### ISSUE THREAD

**Issue by NicoJuicy** [envato/wp-envato-market#79]
Did nothing out of the ordinary. Just trying to update the theme through the envato market plugin.

Haven't updated to Wordpress 4.7 yet 

Request

    POST http://***/wp-admin/admin-ajax.php HTTP/1.1
    Host: ***
    Connection: keep-alive
    Content-Length: 120
    Accept: */*
    Origin: **
    X-Requested-With: XMLHttpRequest
    User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8
    DNT: 1
    Referer: http://***/wp-admin/admin.php?page=envato-market
    Accept-Encoding: gzip, deflate
    Accept-Language: nl,en-US;q=0.8,en;q=0.6,fr;q=0.4
    Cookie:     hidden
     _ajax_nonce=something&theme=flatsome&username=&password=&connection_type=&public_key=&private_key=&action=upgrade-theme

Response:

    {"success":false,"data":{"flatsome":true}}

Any steps on how i can help or what i should do?

**Comment by joaoreynolds** [comment]
I don't get an error `500`, while it is a `200` status the response is `{success: false, data: {infinite: true}}`

**Comment by dtbaker** [comment]
Plugin update coming next week to solve this.
