### ISSUE TITLE
The Token or Item ID is incorrect. 

### ISSUE THREAD

**Issue by matt-buzz** [envato/wp-envato-market#80]
I have created a site, add Single Use OAuth Personal Tokens for all the themes and the plugins i needed to, but one plugin will just not work, all i get it "The Token or Item ID is incorrect." I am unsure how as the rest work fine, using the same process, can anyone help?

**Comment by diloreto** [comment]
Same for me - plugin worked fine on other wordpress sites. I cannot add a token globally or for a single item. Did something change recently?

**Comment by onebelarusianguy** [comment]
+1

**Comment by amber-c** [comment]
+1

Also getting this same error.  Cannot add Global or Personal Tokens.

**Comment by onebelarusianguy** [comment]
@amber-c I found the solution. Build token with this http://build.envato.com/create-token/ with all checked checkboxes for sure.

**Comment by amber-c** [comment]
@onebelarusianguy That didn't work for me unfortunately.  Just tried a new token with all items checked (tested global and single item) and it still spits back the following for Global:

> The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions.

or this for Single:

> The Token or Item ID is incorrect.

**Comment by onebelarusianguy** [comment]
I've also faced with this. Try again with new key, or wait some time. Ultimately it should work

**Comment by onebelarusianguy** [comment]
@amber-c I've also faced with this. Try again with new key, or wait some time. Ultimately it should work

**Comment by matt-buzz** [comment]
Still no change for me, have tried everything! Anyone have any other ideas?

**Comment by fatherb** [comment]
+1

**Comment by BigRedBear** [comment]
Hello everyone. I think I might have found a solution to the issue above if no one else found something this is. http://wpthemego.com/blog/wordpress-tips-tutorials/auto-update-themes-plugins-envato-market-plugin.html

**Comment by dtbaker** [comment]
Plugin update coming next week to solve this.
