### ISSUE TITLE
"Activate the Envato Market plugin" Link Broke

### ISSUE THREAD

**Issue by diloreto** [envato/wp-envato-market#81]
After this plugin is activated another link shows up at the top of the page, "Activate the Envato Market plugin to get updates for your ThemeForest and CodeCanyon items.", but when I click it, all I see is an error page saying "Plugin file does not exist.". Was the plugin checked on the latest version of WP? 

Also I cannot connect an API token any longer for my new install. Could you add more verbose error messages or actions to take? Thanks!

**Comment by JosKlever** [comment]
Make sure you installed the plugin in the correct folder. That should be envato-market. This goes wrong, when you download the wrong link. See the instructions at http://envato.github.io/wp-envato-market/

**Comment by byronyasgur** [comment]
Is there any way to change this in any way. Naturally people will click the Github "Download ZIP" button,
