### ISSUE TITLE
Updating to https

### ISSUE THREAD

**Issue by bkuhl** [envato/wp-envato-market#82]
I updated my site's URL to https and have verified `is_ssl()` returns true within Wordpress.  I'm seeing the following errors in my site as I browse the admin area:

```
Mixed Content: The page at 'https://MYSITE/wp-admin/admin.php?page=envato-wordpress-toolkit&tab=settings' was loaded over HTTPS, but requested an insecure font 'http://MYSITE/wp-content/plugins/envato-wordpress-toolkit-master/assets/fonts/envato.ttf?20141121'. This request has been blocked; the content must be served over HTTPS.
```

I've re-saved the settings to see if that would update this URL but it doesn't help.  How can I ensure this is changed to load assets via https?

**Comment by JosKlever** [comment]
If it says "envato-wordpress-toolkit-master", you have installed the wrong version. Check the instructions: http://envato.github.io/wp-envato-market/

**Comment by bkuhl** [comment]
Gotcha, thanks!

How come this plugin isn't in the Wordpress plugin database?

**Comment by JosKlever** [comment]
I thought that was because the plugin hasn't any function by itself and is only used for premium products. And that's against the rules for the WP repo.

**Comment by leejacksonltd** [comment]
This issue still exists using http://envato.github.io/wp-envato-market/

**Comment by JosKlever** [comment]
If you get the same error (including the "master" part), you installed the wrong version.
