### ISSUE TITLE
Abandoned

### ISSUE THREAD

**Issue by szepeviktor** [envato/wp-envato-market#85]
@valendesigns Hello!

It this plugin abandoned by Envato?

**Comment by rridder** [comment]
Could be nice if can get get an update again. Theme/plugin updates aren't working anymore, it's stuck on installing.

**Comment by scrobbleme** [comment]
Yep, but you can still install the update using the standard update dialog.

**Comment by jasperf** [comment]
Yeah, updates do not seem to work anymore. As @rridder said it is stuck on installing.

**Comment by szepeviktor** [comment]
@valendesigns Could you point out where to fix it? Maybe someone may contribute.

**Comment by TomAshley303** [comment]
What standard update dialog?

**Comment by TomAshley303** [comment]
Oh, Appearance -> Themes -> Update

**Comment by scrobbleme** [comment]
@TomAshley303 Or Dashboard -> Updates

**Comment by szepeviktor** [comment]
@AaronRutley Where is the original issue?
