### ISSUE TITLE
WP multi-site compatible?

### ISSUE THREAD

**Issue by now4dw** [envato/wp-envato-market#90]
I have been using the old Envato Toolkit plugin which only checks for theme upgrades. I recently installed wp-envato-market on a single site and liked that it also checks for plugin updates.

However, having now installed it on one of my multi-sites (and activating at network level), I see that it is only visible at site level. Is that the intended application?

Thanks

**Comment by tfindley** [comment]
I noticed that on my WP MS install it didn't let me actually pull the updates.

I'd suggest that if Envato Market plugin is isntalled onto a MultiSite instance that it goes into the Network Admin on site-wide activation and allow for updating of themes/plugins.

**Comment by dtbaker** [comment]
Thanks for the feedback, we'll try to get Network Admin menu functioning for the plugin update release next week.

**Comment by now4dw** [comment]
That's great. Thanks.

**Comment by dtbaker** [comment]
Seems to work here but we'll do some more tests before releasing it to the masses. 

https://github.com/envato/wp-envato-market/pull/148

**Comment by primalspace** [comment]
Any update on when this plugin will be WP multi-site compatible? Using version 2.0.0 currently. Was using version 1.8.0 which worked fine with multi-site. Safe to go back to that version until a new version is released for multi-site? Thanks.

**Comment by kevinthekingsson** [comment]
I just installed the latest Envato Market plugin on Multisite, as I was advised to do before installing the premium version of WP-SpamShield, which I had just purchased. But Envato Market is still not available on the multisite menu: so I am stuck part-way through the installation, without any spam protection, having just deleted the old copy of WP-Spamshield, as I thought that might interfere with the setup process. Not happy :-(

**Comment by burgh8wp** [comment]
If you go into any of the sub sites on your multi-site install, you'll see the Envato market tab. If you add the API key there it will allow you to update on that sub site, which looks to update the main plugins/themes folder for updates. But the API removes and doesn't work properly. Really fiddly and definitely has a few bugs for multi-site currently. New version required with updates asap

**Comment by kevinthekingsson** [comment]
Thanks for the suggestion. As I was on the point of going to bed, and didn't want to leave my sites unprotected overnight, I resorted to doing a manual install of WP-Spamshield via the Network Admin dashboard. But when I tried to use Network Enable that failed: so I then had to enable it via the Plugins menu on each sub-domain in turn. Probably messed up all my old settings: but at least have protection working. I think I'll turn to WP-Spamshield tech support for their advice on what to do next, and wait for Envato to sort out Market before attempting to use it again.

**Comment by barartm** [comment]
Nope, this still not working, and they closed the old thread: https://github.com/envato/wp-envato-market/issues/50

Im still using the old envato toolkit until today because this new plugin is not working on multisites... it enable it per site and is annoying to add api keys on all sites and check a update site by site (i have 100+ sites on my multisite), this plugin should work as the old envato toolkit, with a only access from network-admin dashboard and not per site

Also it would be great if you can add multiple envato api-keys for different accounts

**Comment by dtbaker** [comment]
We are releasing version 2.0.1 of the market plugin shortly which is multisite compatible.
