### ISSUE TITLE
Where is Personal Token??

### ISSUE THREAD

**Issue by ben6666** [envato/wp-envato-market#91]
I purchased wordpress theme from Envato, and try to use Envato Market Plugin to update the theme.
when I active the Evnato Market, I should put personal token to connect, right?

but where can I find this token?? is the  API Key, generate at dashbord of Envato account???
I try it, but Envato Plugin told me  the connect is failed.

so, somebody tell me, thanks.

**Comment by dtbaker** [comment]
Plugin update coming next week to solve this.
