### ISSUE TITLE
My theme is not showing update link

### ISSUE THREAD

**Issue by mswebworld** [envato/wp-envato-market#92]
Theme URL : https://themeforest.net/item/kidsworld-children-kindergarten-wordpress-theme-for-nursery-preschool-child-care-centers/14851297/comments

One of my buyer report a bug that she is not able to update theme from envato market plugin. It is not showing updated version link or any message to update theme with latest version. I tested it and found the issue. 

Is there any specific code/script required to make compatible with theme plugin or any other steps are necessary. 

One more thing I want to add, I updated theme title. It was...

"KidsWorld - Children Kindergarten WordPress Theme" and now it is

"KidsWorld - Children Kindergarten WordPress Theme for Nursery, Preschool, Child Care Centers"

Please help me to fix this issue.

Thank you.

**Comment by dtbaker** [comment]
Plugin update coming next week to solve this.
