### ISSUE TITLE
Update Hangs

### ISSUE THREAD

**Issue by TomAshley303** [envato/wp-envato-market#93]
I just installed this plugin, input my API key, and clicked to update my theme. The updating progress indicator keeps loading, I don't know what's happened: http://storage5.static.itmages.com/i/17/0419/h_1492585175_3762056_a065dee5c7.png

I'm scared.

**Comment by TomAshley303** [comment]
Apparently we're abandoned: https://github.com/envato/wp-envato-market/issues/85 . Maybe I'll work on it. Let's see what we can see.

**Comment by KingJP** [comment]
Hi @TomAshley303 
I am using the plugin on several Websites. The "Workaround" for you problem is to click the Update Button twice. Then the update will work.
