### ISSUE TITLE
No multiple site checks? Why do we have to use this plugin?

### ISSUE THREAD

**Issue by meta4creations** [envato/wp-envato-market#95]
I am uploading a new theme to TF and had incorporated EDD to run auto-updates for the theme. Unfortunately the reviewer said I was not able to use EDD and had to use this plugin for auto-updates.

I'd rather not use this plugin because there are no checks for multiple sites... Once this plugin is installed on a users site and they add their Token, they can install any and all purchases on every single site they run.

The solution I had with EDD limited user's to license activation on only 1 site, which is what their license is for. I'd be fine with using this plugin if they had some sort of a site check to ensure people aren't using a single site license on multiple sites.

**Comment by dtbaker** [comment]
We're hoping to release more tooling for authors around updates in the future. Please keep an eye on https://envato.com/market-plugin/
