### ISSUE TITLE
The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions.

### ISSUE THREAD

**Issue by Cambrilo** [envato/wp-envato-market#96]
I have a problem with Envato Market plugin. I didn't get update a WP theme. When I make a Test API Connection I receive a following message: "The OAuth Personal Token could not be verified. Please check that the Token has been entered correctly and has the minimum required permissions."

Before all was fine and nothing changed.

**Comment by Kiwi1919** [comment]
Hi,
 I have the same issue, but it has been from the moment I installed the plug in. I have WordPress 4.8, all plug-ins are up to date.

**Comment by firelite** [comment]
Same issue...

**Comment by lonefox1** [comment]
Same issue...

**Comment by ossigeno** [comment]
Same issue. Not a useful error message.

**Comment by dtbaker** [comment]
We have a plugin update coming next week to solve this issue.
