### ISSUE TITLE
Unable to update theme or the market plugin

### ISSUE THREAD

**Issue by harmonbro** [envato/wp-envato-market#99]
Hello Team,
I have been trying to update the wordpress theme. I get this error message. Problems started after the WooCommerce got updated and in the process we have been asked to update the Theme, for it work well with the WOO C. Currently we are unable to update the theme.

Download failed. cURL error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

**Comment by KingJP** [comment]
It seems there is a problem with cURL on your server. Are you using the wp-envato-market Wordpress Plugin?

**Comment by harmonbro** [comment]
We are using WooCommerce plugin and just had it updated 2 days ago and we are trying to update the theme as well but in the process we are unable to update the theme as the update icon just keeps rotating and never updates.

**Comment by harmonbro** [comment]
Also unable to update the WooZone plugin as well 
<img width="1238" alt="screen shot 2017-05-03 at 9 01 10 am" src="https://cloud.githubusercontent.com/assets/28303434/25647383/21c3e43e-2fdf-11e7-89ac-31ac65c53579.png">

**Comment by harmonbro** [comment]
Please help us on this issue

**Comment by harmonbro** [comment]
Can we have some support and help on this please

**Comment by JosKlever** [comment]
This is not an issue of the Envato Market plugin. Ask your webhost to update the server software like cURL and OpenSSL. It's using old software that's not secure and therefore not supported anymore by Envato.

**Comment by harmonbro** [comment]
Thanks Jos. Will check with the hosting guys.

**Comment by harmonbro** [comment]
Hi Jos,
Checked with the hosting guys and they have an issue updating them on a shared server but it is only possible on a dedicated server. Which unfortunately we dont have as we have taken up shared server options. 

IS there any way that this can be sorted out please. Kindly help us out.

**Comment by JosKlever** [comment]
That means that they are forcing you to use old software. Even a shared environment should get it's updates. So you should ask them to migrate your account to a server that has the required updates or you should consider to move to a different host.

**Comment by harmonbro** [comment]
Got it thanks Jos

**Comment by Cajs** [comment]
@harmonbro Using an old version of openssl leaves your system vulnerable too. If they can't update you, please don't ignore it. You should move to another host if they refuse to update or move you to an updated server.

**Comment by harmonbro** [comment]
Will this version work?

OpenSSL 1.0.1
cURL Information 7.36.0 
TLSv1.2

**Comment by JosKlever** [comment]
I'm not sure, because it doesn't seem te be te latest version, but if it's higher than before, it can only be better.

**Comment by harmonbro** [comment]
Jos can you give me some details on the latest version numbers please.

**Comment by JosKlever** [comment]
I'm not the expert here, but if you search on Google you can find information about versions.

**Comment by harmonbro** [comment]
Thanks for everything Jos

**Comment by dtbaker** [comment]
We have a plugin update coming next week to solve this issue.
